"""Training examples for the assistant's paraphrase model (see assistant.knn_intent).

The precise rules in assistant.py catch the clear cases. These examples teach the model the
many other ways people phrase the same needs, so a question the rules miss still lands on the
right tool -- and a question that resembles nothing here is asked about, not guessed.
Numbers are masked before matching, so "5 lakh" and "7 lakh" are the same to the model.
Keep the held-out evaluation sentences in tests/test_assistant_eval.py out of this file.
"""

EXAMPLES: dict[str, list[str]] = {
    "fund_overlap": [
        "do my two mutual funds hold the same shares",
        "are these funds basically the same thing",
        "am i paying for the same stocks twice",
        "how similar are these two funds",
        "do these schemes own the same companies",
        "is it pointless to hold both funds",
        "which of my funds are redundant",
        "compare the holdings of two funds",
        "how much do two funds have in common",
        "is my second fund just a copy of the first",
        "do i need both of these funds",
        "check whether my funds duplicate each other",
        "which funds overlap the most",
        "how diversified are my mutual funds against each other",
        "are my funds too alike",
        "which of my mutual funds overlap",
        "does bluechip fund b hold what large cap fund a holds",
        "overlap between large cap fund a and flexi cap fund c",
    ],
    "fund_list": [
        "which funds can you compare",
        "show me the funds you know about",
        "what mutual funds do you have data for",
        "list the available funds",
        "what funds are there to pick from",
        "give me the list of funds",
        "which schemes can i check",
    ],
    "fund_info": [
        "which companies are in the consumption fund",
        "list the stocks held by the bluechip fund",
        "what shares make up the flexi cap fund",

        "what stocks are inside the banking fund",
        "top holdings of the technology fund",
        "what does the flexi cap fund own",
        "what is in the nifty index fund",
        "show me what the healthcare fund holds",
    ],
    "fund_vs_direct": [
        "how many of my own shares are already in this fund",
        "does this fund contain the stocks i bought directly",
        "is the fund repeating my direct holdings",

        "which of my stocks are already in that fund",
        "do i already own these shares through a mutual fund",
        "how much of my direct holdings is inside the index fund",
        "would this fund repeat the stocks i own",
        "do my shares show up inside the fund",
    ],
    "my_funds_add": [
        "i own large cap fund a and bluechip fund b",
        "i hold the nifty index fund",
        "i have invested in the flexi cap fund",
        "my funds are the technology fund and the banking fund",
        "add the healthcare fund to my funds",
        "i put money in the consumption fund",
    ],
    "my_funds_remove": [
        "remove the bluechip fund from my funds",
        "i sold my flexi cap fund",
        "forget the technology fund",
        "clear all my saved funds",
    ],
    "my_funds_show": [
        "which funds have i saved",
        "show my funds",
        "what mutual funds do i own according to you",
        "list my funds",
    ],
    "fee_drag": [
        "why are direct plans said to be better",
        "what is the long term effect of paying a higher expense ratio",
        "how much do i give away in charges over the years",
        "is it worth paying more for an actively managed fund",

        "how much does a 2 percent fund fee cost me over 20 years",
        "what do mutual fund charges do to my returns",
        "is a high expense ratio really that bad",
        "how much will fees eat from my sip",
        "direct plan versus regular plan difference in the long run",
        "what is the cost of a 1.5 percent expense ratio over 10 years",
        "what does paying a fund manager cost over time",
        "do small fees matter over decades",
        "how much money do i lose to fees",
        "fee impact on 10000 a month sip for 15 years",
        "is an index fund cheaper in the long run",
        "what is the real cost of a high fee fund",
    ],
    "emergency": [
        "how long can i survive if i lose my job",
        "how many months will my savings last",
        "do i have enough emergency money",
        "if my salary stops how long can i manage",
        "is my rainy day fund big enough",
        "how long will my cash last if i spend 40000 a month",
        "what happens to my savings if i get laid off",
        "how much emergency fund should i keep",
        "will my savings cover six months",
        "i have 3 lakh saved and spend 40000 a month how long will it last",
        "how long before my money runs out without income",
        "runway if i quit my job",
    ],
    "goal": [
        "what could my monthly investment grow into",
        "how much will i have after twenty years of investing",
        "can my savings plan reach my target",
        "how much corpus will i build",

        "will i reach 50 lakh in 15 years",
        "can my sip build a crore by retirement",
        "how long will it take to reach 1 crore",
        "is 10000 a month enough to get 50 lakh",
        "what will my investment be worth in 20 years",
        "am i on track for retirement",
        "how much should i invest every month to reach my goal",
        "will my portfolio grow to 2 crore",
        "if i invest 20000 monthly for 10 years what do i get",
        "can i become a crorepati with a sip",
        "will i have enough to retire",
        "how likely is it that i hit my target",
    ],
    "panic": [
        "simulate me exiting at the worst point of the crash",
        "what would my money be if i had cashed out at the bottom",
        "compare selling in a panic with staying invested through a crash",

        "what if i had sold during the covid crash",
        "would i have been better off selling at the bottom",
        "what happens if i panic sell in a crash",
        "should i sell when the market falls or hold on",
        "how bad is panic selling",
        "had i exited in march 2020 what would i have today",
        "does selling in a fall hurt me",
        "if i bailed in the 2022 selloff what then",
        "replay a crash and show me selling versus holding",
        "what is the cost of selling at the low",
    ],
    "digest": [
        "give me a spoken summary of my portfolio this week",
        "read out my weekly portfolio summary",
        "what happened to my investments over the last seven days",

        "give me my weekly digest",
        "how did my portfolio do this week",
        "summarise my week",
        "read me the weekly update",
        "give me a one minute briefing",
        "catch me up on my money this week",
        "what is my weekly summary",
        "speak my digest in hindi",
    ],
    "scam_help": [
        "how can i tell if a bank call is genuine",
        "is it safe to click this kyc link",
        "someone is pressuring me to send money urgently",
        "a caller says my account is frozen",
        "i got an sms asking me to verify my account",
        "they asked me for my card details on the phone",
        "what to do when a stranger asks for upi pin",

        "someone called asking for my otp",
        "a man says he is from the bank and my kyc has expired",
        "i got a call about digital arrest",
        "i think i was scammed",
        "a stranger asked me to install anydesk",
        "i received a suspicious message with a link",
        "they asked me to transfer money to a safe account",
        "what do i do if i got cheated online",
        "my parent got a fake police call",
        "i shared my otp by mistake",
        "somebody claims there is a parcel in my name with drugs",
        "is this phone call a scam",
    ],
    "tip_scan": [
        "is this telegram tip real",
        "check this whatsapp stock message for me",
        "a group promises guaranteed profit is it legit",
        "someone on instagram says double your money is it safe",
        "scan this tip",
        "can i trust this stock advice i got in a forward",
        "this advisor promises 40 percent a month is that genuine",
        "verify this message about a sure shot stock",
    ],
    "predict": [
        "which share will give me ten times my money",
        "guarantee me a return on some stock",
        "what will the sensex do next week",
        "which stock is a sure winner",
        "tell me what to buy to get rich quickly",

        "which stock will double next year",
        "tell me a multibagger",
        "where will nifty be next month",
        "will the market crash tomorrow",
        "which share should i buy today for quick profit",
        "what is the price target for tcs",
        "predict the market",
        "will reliance go up this week",
    ],
    "ledger": [
        "is my trade record safe from tampering",
        "show me the audit trail",
        "has anyone edited my past trades",
        "can the history of my trades be changed",
        "verify the ledger",
    ],
    "help": [
        "what kind of questions can i put to you",
        "what are the things you can help with",
        "give me some ideas on what to ask",
        "i am new here what can i do",

        "what can you do for me",
        "how do i use this",
        "what should i ask you",
        "tell me your features",
        "what are you capable of",
        "i do not know where to start",
    ],
    "chitchat": [
        "hello", "hi there", "good morning", "thanks a lot", "thank you so much", "okay great", "bye", "namaste",
    ],
    "out_of_scope": [
        "where can i find good food nearby",
        "tell me about the latest movie",
        "what is the distance to the moon",
        "suggest a holiday destination",
        "who is the richest person",
        "help me with my maths homework",

        "what is the weather today",
        "tell me a joke",
        "who won the cricket match",
        "who is the prime minister",
        "play some music",
        "what is the capital of france",
        "write me a poem",
        "how do i cook biryani",
        "what time is it",
        "translate this sentence into french",
    ],
    # --- the original explainer's questions -------------------------------------------------
    "xray": [
        "how am i doing",
        "how is my portfolio",
        "give me a health check of my investments",
        "review my holdings",
        "summarise my portfolio",
        "is my portfolio okay",
        "how healthy are my investments",
        "what does my portfolio look like",
        "give me an overview of my money",
        "grade my portfolio",
    ],
    "why": [
        "what are the biggest risks in my portfolio",
        "where is my portfolio weak",
        "what is hurting my score",
        "which risks should i worry about",
        "what is dragging my grade down",

        "why is my risk high",
        "what is wrong with my portfolio",
        "why did i get this score",
        "what is the biggest problem in my holdings",
        "why is my grade low",
        "what concerns you about my investments",
    ],
    "fix": [
        "what should i sell",
        "what can i trim to reduce risk",
        "how do i fix my portfolio",
        "what should i do about my concentration",
        "which holding should i reduce",
        "tell me what to change",
    ],
    "stress": [
        "what if the market drops 20 percent",
        "what happens if technology falls 30 percent",
        "what happened in covid",
        "how would my portfolio do in a crash",
        "what is my worst case",
        "show me how i would do in a downturn",
        "what if banks fall",
        "stress test my holdings",
    ],
    "diversification": [
        "am i overexposed to a single industry",
        "is too much of my money riding on one sector",
        "are all my investments in the same type of company",

        "am i putting too many eggs in one basket",
        "is too much of my money in a single industry",
        "is my portfolio too tilted to one sector",
        "do i own enough different kinds of companies",
        "how spread out am i",

        "am i diversified",
        "is my money spread out enough",
        "do i have too much in one sector",
        "am i too concentrated",
        "is my portfolio balanced across industries",
        "how diversified is my portfolio",
    ],
    "correlation": [
        "do any of my holdings behave alike",
        "which of my shares rise and fall together",
        "are two of my stocks basically the same bet",
        "which stocks in my portfolio are linked",

        "what moves together in my portfolio",
        "which of my stocks move in step",
        "does infosys move with tcs",
        "which holdings are the same bet",
        "what does tcs move with",
    ],
    "should_buy": [
        "should i buy more tcs",
        "is it a good idea to add infosys",
        "can i invest in reliance",
        "would adding ongc help me",
        "is it worth buying hdfc bank",
        "should i pick up some itc",
    ],
    "define": [
        "what is an exchange traded fund",
        "what is a lock in period",
        "what does nav of a mutual fund mean",
        "what is a dividend",
        "what is inflation",

        "what is beta",
        "what does drawdown mean",
        "explain volatility",
        "what is a sector cap",
        "what is nav",
        "what is concentration risk",
    ],
    "simplify": [
        "explain that simply",
        "i do not understand can you simplify",
        "say that in plain english",
        "make it simpler",
        "eli5",
    ],
}
