"""Hand-written, checked explanations for the money questions people actually ask.

Why a library and not a language model: an answer about money must be right every time, so each explanation here was
written once, in English and Hindi, and is shown as written. A model is only ever used to PICK which entry fits a
question (backend/understand.py); it never writes the answer and never supplies a number.

Rules that keep it honest:
  * a rule of thumb is called a rule of thumb, with the reason it exists and when it does not apply;
  * a rate, a limit or a tax rate that can change carries "as of" wording and tells the person to confirm it;
  * nothing here tells anyone to buy or sell a particular security.
"""
from __future__ import annotations

import re
from typing import Any


def C(cid: str, cat: str, rx: str, questions: list[str], head: tuple[str, str], points: tuple[list[str], list[str]],
      watch: tuple[str, str], follow: list[tuple[str, str]], table: dict | None = None, example: tuple[str, str] | None = None,
      tool: tuple[str, str, str, dict] | None = None, tour: str | None = None) -> dict[str, Any]:
    return {"id": cid, "cat": cat, "rx": re.compile(rx, re.I), "q": questions,
            "head": {"en": head[0], "hi": head[1]}, "points": {"en": points[0], "hi": points[1]},
            "watch": {"en": watch[0], "hi": watch[1]}, "follow": follow, "table": table,
            "example": None if example is None else {"en": example[0], "hi": example[1]},
            "tool": tool, "tour": tour}


CONCEPTS: list[dict[str, Any]] = [
    C("sip_vs_lumpsum", "Investing basics", r"\b(sip|systematic)\b.{0,40}\b(lump ?sum|one[- ]time|at once)\b|\b(lump ?sum|one[- ]time)\b.{0,40}\b(sip|monthly)\b|\bsip or lump ?sum\b",
      ["what is the difference between sip and lumpsum", "should I invest through sip or lump sum", "sip vs lump sum investment which is better", "is monthly investing better than investing all at once"],
      ("A SIP invests a fixed amount every month; a lump sum invests everything at once. Neither is better in every case: it depends on when your money arrives and how much a fall would worry you.",
       "SIP हर महीने एक तय रक़म लगाती है; एकमुश्त एक बार में सब लगाता है। हर हाल में कोई एक बेहतर नहीं: यह इस पर टिका है कि आपका पैसा कब आता है और गिरावट आपको कितना बेचैन करती है।"),
      (["SIP: you buy a little each month, so you buy more units when prices are low and fewer when high. It suits a monthly salary and removes the stress of picking a day.",
        "Lump sum: if you already hold the money, all of it starts working from day one. Historically, when markets mostly rise, investing early has often done better, but a fall right after you invest hurts more.",
        "A middle path if you hold a large sum: put it in a safe place and move it into the fund in equal parts over 6 to 12 months (a 'systematic transfer').",
        "For the same total, your return depends far more on how long you stay invested and on the fund's fee than on SIP versus lump sum."],
       ["SIP: आप हर महीने थोड़ा ख़रीदते हैं, इसलिए भाव नीचे होने पर ज़्यादा यूनिट और ऊपर होने पर कम मिलते हैं। यह मासिक वेतन के लिए ठीक है और दिन चुनने की चिंता हटा देती है।",
        "एकमुश्त: पैसा पहले से हो तो पूरा पहले दिन से काम पर लग जाता है। इतिहास में, जब बाज़ार ज़्यादातर बढ़े हैं, जल्दी लगाना अक्सर बेहतर रहा, पर लगाने के ठीक बाद गिरावट ज़्यादा चुभती है।",
        "बड़ी रक़म हो तो बीच का रास्ता: उसे सुरक्षित जगह रखिए और 6 से 12 महीनों में बराबर हिस्सों में फ़ंड में डालिए (सिस्टमैटिक ट्रांसफ़र)।",
        "उसी कुल रक़म पर आपका रिटर्न SIP या एकमुश्त से कहीं ज़्यादा इस पर निर्भर है कि आप कितने समय टिके रहे और फ़ंड की फ़ीस कितनी है।"]),
      ("Neither method protects you from a fall. Money you need within about three years should not be in an equity fund either way.",
       "कोई भी तरीक़ा गिरावट से नहीं बचाता। जिस पैसे की लगभग तीन साल में ज़रूरत है, उसे दोनों तरीक़ों में इक्विटी फ़ंड में नहीं रखना चाहिए।"),
      [("Will 10000 a month reach 50 lakh in 15 years?", "10000 महीने की SIP से 15 साल में 50 लाख बनेंगे?"), ("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")],
      table={"columns": {"en": ["", "SIP", "Lump sum"], "hi": ["", "SIP", "एकमुश्त"]},
             "rows": {"en": [["Money comes", "Monthly", "All at once"], ["Timing worry", "Low", "Higher"], ["Starts working", "Gradually", "Immediately"], ["Best when", "You earn a salary", "You already hold the sum"]],
                      "hi": [["पैसा आता है", "हर महीने", "एक साथ"], ["समय की चिंता", "कम", "ज़्यादा"], ["काम शुरू", "धीरे-धीरे", "तुरंत"], ["कब बेहतर", "वेतन से बचत हो", "रक़म पहले से हो"]]}},
      tool=("learn", "Test your own SIP", "अपनी SIP परखिए", {})),

    C("fd_vs_mf", "Investing basics", r"\bwhat (should|do|can|to) (i|we)( do)? with (my |the |this |a )?(\d[\d.,]*\s?)?(lakh|lakhs|crore|money|savings|bonus|windfall|inheritance|corpus|amount|sum)\b|\bi have\b.{0,25}\b(lakh|lakhs|crore|savings|money)\b.{0,40}\b(invest|put|park|where|what|how)\b|\bwhere (to|should i|can i) (invest|put|park)\b|\b(fd|fixed deposit|fds)\b.{0,50}\b(mutual funds?|mf|equity|stocks?|sip)\b|\b(mutual funds?|equity|stocks?)\b.{0,50}\b(fd|fixed deposit)\b|\b(split|divide|allocate|distribute|put)\b.{0,40}\b(between|across|into)\b.{0,40}\b(fd|funds?|equity|debt|gold)\b",
      ["how should I split my money between fd and mutual funds", "fd or mutual fund where should i put my savings", "how much in fixed deposit and how much in equity", "is mutual fund better than fixed deposit"],
      ("There is no single split that is right for everyone. A useful way to decide is by when you will need the money: near-term money belongs in safe places, long-term money can take equity's ups and downs.",
       "सबके लिए कोई एक सही बँटवारा नहीं होता। तय करने का काम का तरीक़ा यह है कि पैसा कब चाहिए: नज़दीकी पैसा सुरक्षित जगह, लंबे समय का पैसा इक्विटी के उतार-चढ़ाव सह सकता है।"),
      (["Needed within 1 to 3 years (a wedding, school fees, a deposit for a house): fixed deposits, savings, liquid or short-term debt funds. A fall in equity could land just when you need to sell.",
        "Needed in 3 to 5 years: a mix, leaning to safe. Some people use a hybrid fund.",
        "Needed in 7 years or more (retirement, a child's college): equity funds, ideally low-cost index funds, can take a larger share because time smooths out the falls.",
        "First keep an emergency fund of 6 months' expenses in a safe place. Only money beyond that and beyond near-term goals is 'investable'.",
        "Fixed deposit interest is added to your income and taxed at your slab. Equity gains are taxed at lower rates after a year, which is one more reason equity suits long horizons."],
       ["1 से 3 साल में चाहिए (शादी, स्कूल फ़ीस, घर का एडवांस): फ़िक्स्ड डिपॉज़िट, बचत खाता, लिक्विड या छोटी अवधि के डेट फ़ंड। इक्विटी की गिरावट ठीक बेचने के समय आ सकती है।",
        "3 से 5 साल में चाहिए: मिला-जुला, सुरक्षित की ओर झुका हुआ। कुछ लोग हाइब्रिड फ़ंड लेते हैं।",
        "7 साल या ज़्यादा में चाहिए (रिटायरमेंट, बच्चे की कॉलेज फ़ीस): इक्विटी फ़ंड, ख़ासकर कम फ़ीस वाले इंडेक्स फ़ंड, बड़ा हिस्सा ले सकते हैं क्योंकि समय गिरावट को सँभाल लेता है।",
        "सबसे पहले 6 महीने के ख़र्च जितना इमरजेंसी फ़ंड सुरक्षित जगह रखिए। उसके और नज़दीकी लक्ष्यों के बाद का पैसा ही 'निवेश योग्य' है।",
        "फ़िक्स्ड डिपॉज़िट का ब्याज आपकी आय में जुड़कर आपके स्लैब पर कर पाता है। इक्विटी के लाभ पर एक साल बाद कम दर लगती है, जो इक्विटी के लंबे समय के लिए ठीक होने का एक और कारण है।"]),
      ("This is general education, not advice for your situation. I will not name a percentage for you without knowing your goals, dates and what a fall would do to you.",
       "यह सामान्य जानकारी है, आपकी स्थिति की सलाह नहीं। आपके लक्ष्य, तारीख़ें और गिरावट का असर जाने बिना मैं कोई प्रतिशत नहीं बताऊँगा।"),
      [("How long will 3 lakh last if I spend 40000 a month?", "3 लाख रुपये 40000 महीने के ख़र्च पर कितना चलेंगे?"), ("Am I diversified?", "क्या मेरा पैसा अलग-अलग जगह बँटा है?")],
      table={"columns": {"en": ["When you need it", "Where it usually sits"], "hi": ["कब चाहिए", "आम तौर पर कहाँ"]},
             "rows": {"en": [["Within 1-3 years", "FD, savings, liquid/short debt"], ["3-5 years", "Mostly safe, some hybrid/equity"], ["7+ years", "Mostly equity (index funds)"], ["Emergency", "Savings/liquid, 6 months of costs"]],
                      "hi": [["1-3 साल में", "FD, बचत, लिक्विड/छोटी अवधि डेट"], ["3-5 साल", "ज़्यादातर सुरक्षित, कुछ हाइब्रिड/इक्विटी"], ["7+ साल", "ज़्यादातर इक्विटी (इंडेक्स फ़ंड)"], ["आपात", "बचत/लिक्विड, 6 महीने का ख़र्च"]]}},
      tool=("practice", "Check your emergency cushion", "इमरजेंसी गद्दी जाँचिए", {"tool": "emergency"})),

    C("mutual_fund", "Funds", r"\b(what('?s| is)|explain|how (does|do))\b.{0,20}\b(mutual funds?|mf)\b|\bmutual funds? (work|basics|explained|for beginners)\b|\bnav\b.{0,15}\b(mean|work|calculated)\b",
      ["what is a mutual fund", "how do mutual funds work", "explain mutual fund for a beginner", "what is nav in mutual fund"],
      ("A mutual fund pools money from many people and a professional manager invests it in a basket of shares or bonds. You own 'units' of that basket, and each unit's price is called the NAV.",
       "म्यूचुअल फ़ंड बहुत से लोगों का पैसा जोड़ता है और एक पेशेवर मैनेजर उसे शेयरों या बॉन्ड की टोकरी में लगाता है। आप उस टोकरी की 'यूनिट' के मालिक होते हैं और हर यूनिट की क़ीमत NAV कहलाती है।"),
      (["You put in ₹ and get units at that day's NAV. Units × NAV = what your holding is worth.",
        "Types: equity funds (shares), debt funds (bonds), hybrid (both), index funds (copy an index like Nifty 50 with no manager's picking) and ETFs (index-like, traded on the exchange).",
        "Costs: the expense ratio is deducted from the fund's value each year. Direct plans charge less than regular plans because there is no distributor commission.",
        "Regulated by SEBI; your money stays in the fund, not with the company that runs it.",
        "Returns are not guaranteed; the fund's value rises and falls with what it holds."],
       ["आप ₹ डालते हैं और उस दिन के NAV पर यूनिट पाते हैं। यूनिट × NAV = आपके निवेश का मूल्य।",
        "प्रकार: इक्विटी फ़ंड (शेयर), डेट फ़ंड (बॉन्ड), हाइब्रिड (दोनों), इंडेक्स फ़ंड (निफ़्टी 50 जैसा सूचकांक बिना मैनेजर की पसंद के दोहराते हैं) और ETF (इंडेक्स जैसे, एक्सचेंज पर बिकते)।",
        "लागत: एक्सपेंस रेशियो हर साल फ़ंड के मूल्य से कटता है। डायरेक्ट प्लान रेगुलर से सस्ते होते हैं क्योंकि इसमें वितरक का कमीशन नहीं।",
        "इसे SEBI नियंत्रित करता है; आपका पैसा फ़ंड में रहता है, उसे चलाने वाली कंपनी के पास नहीं।",
        "रिटर्न की गारंटी नहीं; फ़ंड का मूल्य उसकी होल्डिंग के साथ चढ़ता-उतरता है।"]),
      ("A low NAV does not mean a cheap fund. NAV is just the price per unit, and it says nothing about quality or future return.",
       "कम NAV का मतलब सस्ता फ़ंड नहीं है। NAV सिर्फ़ प्रति यूनिट क़ीमत है, यह गुणवत्ता या आगे के रिटर्न के बारे में कुछ नहीं बताता।"),
      [("Which funds do you have?", "आपके पास कौन से म्यूचुअल फ़ंड हैं?"), ("Which of my mutual funds overlap?", "मेरे कौन से म्यूचुअल फ़ंड आपस में मिलते हैं?")],
      tool=("practice", "Compare two funds", "दो फ़ंड की तुलना", {"tool": "overlap"})),

    C("direct_vs_regular", "Funds", r"\b(direct|regular)\b.{0,25}\b(plan|plans|fund|funds|growth)\b|\bdirect (vs|or|versus) regular\b|\b(idcw|growth) (vs|or|option)\b",
      ["what is the difference between direct and regular plan", "should I choose direct or regular mutual fund", "why is regular plan costlier"],
      ("A direct plan and a regular plan hold exactly the same investments. The only difference is that a regular plan pays a distributor's commission out of your money every year, so its returns are lower by about that much.",
       "डायरेक्ट और रेगुलर प्लान में बिल्कुल वही निवेश होते हैं। फ़र्क़ सिर्फ़ इतना है कि रेगुलर प्लान हर साल आपके पैसे से वितरक का कमीशन देता है, इसलिए उसका रिटर्न लगभग उतना कम रहता है।"),
      (["The gap is often around 0.5 to 1 percentage point a year. Over 20 years that can take a large share of your gains.",
        "Direct: you choose and manage yourself (apps, the fund house's site). Regular: an agent or bank helps you and is paid by the fund.",
        "Pick regular only if the help is worth the cost to you, for example if you would otherwise not invest at all or would panic-sell. A flat-fee advisor registered with SEBI is another option.",
        "'Growth' reinvests profit inside the fund. 'IDCW' (formerly dividend) pays out part of your own money as cash and is taxed in your hands."],
       ["यह अंतर अक्सर सालाना लगभग 0.5 से 1 प्रतिशत अंक होता है। 20 साल में यह आपके लाभ का बड़ा हिस्सा ले सकता है।",
        "डायरेक्ट: आप ख़ुद चुनते और सँभालते हैं (ऐप, फ़ंड कंपनी की साइट)। रेगुलर: एजेंट या बैंक मदद करता है और फ़ंड से कमीशन पाता है।",
        "रेगुलर तभी लीजिए जब मदद की क़ीमत आपके लिए वाजिब हो, जैसे वरना आप निवेश ही न करते या घबराकर बेच देते। SEBI-पंजीकृत फ़्लैट-फ़ीस सलाहकार एक और विकल्प है।",
        "'ग्रोथ' मुनाफ़ा फ़ंड के भीतर ही दोबारा लगाता है। 'IDCW' (पहले डिविडेंड) आपके ही पैसे का हिस्सा नक़द लौटाता है और आपके हाथ में कर लगता है।"]),
      ("Look at the exact figures on the fund's factsheet: the gap differs between funds.", "फ़ंड की फ़ैक्टशीट में ठीक आँकड़े देखिए: फ़ंड के अनुसार अंतर अलग होता है।"),
      [("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")],
      tool=("practice", "See what a fee costs", "फ़ीस की क़ीमत देखिए", {"tool": "fee"}), tour="fee"),

    C("index_fund", "Funds", r"\b(index funds?|nifty (50 )?(index|etf)|passive (fund|investing)|passive vs active|active vs passive)\b.{0,40}\b(good|better|why|work|should|beginner|cheap|worth|vs|versus|or)\b|\bwhy (are )?index funds\b|\bwhat('?s| is) (an )?index fund\b|\b(active|passive)\b.{0,30}\b(active|passive)\b",
      ["what is an index fund and why is it cheap", "are index funds good for beginners", "active fund vs index fund", "should I pick an index fund"],
      ("An index fund simply copies a market index such as the Nifty 50: it buys the same companies in the same proportions. There is no manager trying to beat the market, so it can charge a very low fee.",
       "इंडेक्स फ़ंड सीधे किसी सूचकांक, जैसे निफ़्टी 50, की नक़ल करता है: वही कंपनियाँ उसी अनुपात में। बाज़ार को हराने की कोशिश करने वाला कोई मैनेजर नहीं, इसलिए फ़ीस बहुत कम रखी जा सकती है।"),
      (["Low cost matters: a fee of about 0.2% versus 1.5% or more compounds into a big difference over decades.",
        "It is automatically diversified across the index's companies.",
        "Most active funds in a category have, over long periods, trailed their index after fees; a few beat it, but it is hard to know in advance which.",
        "Downside: when the market falls, the index fund falls with it. It tracks, it does not protect.",
        "Two index funds on the same index hold the same stocks, so owning both gains you nothing."],
       ["कम लागत मायने रखती है: लगभग 0.2% बनाम 1.5% या ज़्यादा की फ़ीस दशकों में बड़ा अंतर बन जाती है।",
        "यह सूचकांक की कंपनियों में अपने आप बँटा होता है।",
        "किसी श्रेणी के ज़्यादातर सक्रिय फ़ंड लंबे समय में फ़ीस के बाद अपने सूचकांक से पीछे रहे हैं; कुछ आगे निकलते हैं, पर पहले से पता लगाना कठिन है।",
        "कमी: बाज़ार गिरे तो इंडेक्स फ़ंड भी गिरता है। यह साथ चलता है, बचाता नहीं।",
        "एक ही सूचकांक पर दो इंडेक्स फ़ंड एक ही शेयर रखते हैं, इसलिए दोनों लेने से कुछ नहीं मिलता।"]),
      ("Check the 'tracking error': a good index fund stays very close to its index.", "'ट्रैकिंग एरर' देखिए: अच्छा इंडेक्स फ़ंड अपने सूचकांक के बहुत क़रीब रहता है।"),
      [("Which of my mutual funds overlap?", "मेरे कौन से म्यूचुअल फ़ंड आपस में मिलते हैं?"), ("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")],
      tool=("practice", "Compare funds for overlap", "फ़ंड ओवरलैप जाँचिए", {"tool": "overlap"})),

    C("etf_vs_fund", "Funds", r"\betfs?\b.{0,40}\b(vs|versus|or|difference|better|mutual|index)\b|\b(difference between|vs|versus)\b.{0,30}\betf\b|\bwhat('?s| is) (an )?etf\b",
      ["what is an etf", "etf vs index mutual fund", "difference between etf and mutual fund"],
      ("An ETF is a basket of shares that trades on the stock exchange like a single share. Most ETFs copy an index. An index mutual fund does the same job but you buy it from the fund house at the day's NAV.",
       "ETF शेयरों की एक टोकरी है जो एक शेयर की तरह स्टॉक एक्सचेंज पर बिकती है। ज़्यादातर ETF किसी सूचकांक की नक़ल करते हैं। इंडेक्स म्यूचुअल फ़ंड वही काम करता है पर आप उसे फ़ंड कंपनी से उस दिन के NAV पर ख़रीदते हैं।"),
      (["ETF: needs a demat account; you buy at live prices during market hours; usually the lowest fees; no automatic monthly SIP in many apps.",
        "Index mutual fund: no demat needed; easy automatic SIP; price is the end-of-day NAV; fee is slightly higher.",
        "For a beginner who wants a monthly habit, an index mutual fund is simpler. ETFs suit people who already trade through a demat account.",
        "Thinly traded ETFs can have a gap between the price you pay and the true value of the basket."],
       ["ETF: डीमैट खाता चाहिए; बाज़ार के समय लाइव भाव पर ख़रीदते हैं; फ़ीस आम तौर पर सबसे कम; कई ऐप में अपने-आप मासिक SIP नहीं।",
        "इंडेक्स म्यूचुअल फ़ंड: डीमैट नहीं चाहिए; आसान ऑटोमैटिक SIP; भाव दिन के अंत का NAV; फ़ीस थोड़ी ज़्यादा।",
        "जिसे मासिक आदत बनानी है, उस शुरुआती के लिए इंडेक्स म्यूचुअल फ़ंड सरल है। ETF उनके लिए है जो पहले से डीमैट से ट्रेड करते हैं।",
        "कम कारोबार वाले ETF में आपके दिए भाव और टोकरी के असली मूल्य में अंतर हो सकता है।"]),
      ("Both carry market risk. Cheaper does not mean safer.", "दोनों में बाज़ार का जोखिम है। सस्ता होने का मतलब सुरक्षित होना नहीं।"),
      [("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")]),

    C("diversification_idea", "Investing basics", r"\bwhat('?s| is| does)\b.{0,15}\b(diversif\w+|asset allocation)\b|\bwhy (should i |do i need to |is it important to )?diversif\w+\b|\bdon.?t put all (your |my )?eggs\b|\bhow (to|do i) diversif\w+\b|\bwhat is asset allocation\b",
      ["what is diversification", "why should i diversify my investments", "how do I diversify", "what is asset allocation"],
      ("Diversification means not letting one thing decide your outcome: spreading money across different companies, industries and kinds of assets so one bad event cannot hurt everything at once.",
       "विविधीकरण का मतलब है कि कोई एक चीज़ आपका नतीजा तय न करे: पैसा अलग-अलग कंपनियों, उद्योगों और तरह की संपत्तियों में फैलाइए ताकि एक बुरी घटना सब पर एक साथ असर न करे।"),
      (["Count the real spread, not the number of stocks: ten companies in the same industry tend to fall together, so they behave like fewer.",
        "Three layers: across companies, across industries, and across asset types (equity, debt, gold, cash).",
        "A low-cost index fund gives broad spread in one purchase; a single sector fund does the opposite.",
        "Too much spreading is also a cost: dozens of overlapping funds add paperwork and fees without adding safety.",
        "Asset allocation is the bigger decision: how much sits in equity versus safer assets matters more than which stock you pick."],
       ["असली फैलाव गिनिए, शेयरों की संख्या नहीं: एक ही उद्योग की दस कंपनियाँ साथ गिरती हैं, इसलिए वे कम जैसी चलती हैं।",
        "तीन परतें: कंपनियों में, उद्योगों में और संपत्ति के प्रकारों में (इक्विटी, डेट, सोना, नक़द)।",
        "कम फ़ीस वाला इंडेक्स फ़ंड एक ख़रीद में चौड़ा फैलाव देता है; अकेला सेक्टर फ़ंड उलटा करता है।",
        "बहुत ज़्यादा फैलाना भी एक लागत है: दर्जनों एक-दूसरे से मिलते फ़ंड काग़ज़ी काम और फ़ीस बढ़ाते हैं, सुरक्षा नहीं।",
        "एसेट एलोकेशन बड़ा फ़ैसला है: कितना इक्विटी में और कितना सुरक्षित में, यह आप कौन सा शेयर चुनते हैं उससे ज़्यादा मायने रखता है।"]),
      ("Diversification lowers the chance of a big loss from one cause. It does not remove market risk.", "विविधीकरण किसी एक कारण से बड़े नुक़सान की संभावना घटाता है। यह बाज़ार का जोखिम नहीं हटाता।"),
      [("Am I diversified?", "क्या मेरा पैसा अलग-अलग जगह बँटा है?"), ("Which of my stocks move together?", "मेरे कौन से शेयर साथ चलते हैं?")],
      tool=("portfolio", "See how your money is spread", "देखिए आपका पैसा कैसे बँटा है", {})),

    C("compounding", "Investing basics", r"\b(compound\w*|rule of 72|power of compounding|interest on interest|double my money in)\b",
      ["what is compounding", "how does compound interest work", "what is the rule of 72", "how many years to double my money"],
      ("Compounding means your earnings start earning too. Over long periods this snowball is the biggest force in saving, which is why starting early matters more than starting big.",
       "चक्रवृद्धि का मतलब है कि आपकी कमाई भी कमाने लगती है। लंबे समय में यह गोला सबसे बड़ी ताक़त है, इसीलिए जल्दी शुरू करना बड़ी रक़म से शुरू करने से ज़्यादा मायने रखता है।"),
      (["Rule of 72: divide 72 by the yearly return to estimate years to double. At 8% it takes about 9 years; at 12%, about 6.",
        "The same rule works against you: a loan or card at 36% a year doubles what you owe in about 2 years.",
        "Example: ₹10,000 a month for 20 years at 12% a year grows to roughly ₹1 crore, of which you put in ₹24 lakh. Most of the rest is earnings on earnings. (An illustration of arithmetic, not a forecast.)",
        "Starting 10 years later needs a far bigger monthly amount to reach the same goal.",
        "Fees and inflation reduce the real growth, which is why a low fee and a real (after-inflation) view both matter."],
       ["72 का नियम: 72 को सालाना रिटर्न से भाग दीजिए, दोगुना होने के सालों का अंदाज़ा मिलेगा। 8% पर लगभग 9 साल; 12% पर लगभग 6।",
        "यही नियम आपके ख़िलाफ़ भी चलता है: साल के 36% वाला क़र्ज़ या कार्ड लगभग 2 साल में आपकी देनदारी दोगुनी कर देता है।",
        "उदाहरण: 12% सालाना पर महीने के ₹10,000, 20 साल के लिए, लगभग ₹1 करोड़ बनते हैं, जिसमें आपके ₹24 लाख हैं। बाक़ी ज़्यादातर कमाई पर कमाई है। (यह गणित का उदाहरण है, भविष्यवाणी नहीं।)",
        "10 साल देर से शुरू करने पर उसी लक्ष्य के लिए कहीं बड़ी मासिक रक़म चाहिए।",
        "फ़ीस और महँगाई असली बढ़त घटाती हैं, इसलिए कम फ़ीस और महँगाई के बाद की (असली) नज़र, दोनों ज़रूरी हैं।"]),
      ("Returns of 12% are not guaranteed: markets move unevenly, and real results differ year to year.", "12% रिटर्न की गारंटी नहीं: बाज़ार असमान चलते हैं और असली नतीजे साल-दर-साल अलग होते हैं।"),
      [("Will 10000 a month reach 50 lakh in 15 years?", "10000 महीने की SIP से 15 साल में 50 लाख बनेंगे?"), ("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")],
      tool=("learn", "Test a goal", "लक्ष्य परखिए", {})),

    C("inflation", "Investing basics", r"\b(inflation|real return|purchasing power|prices keep rising|value of money)\b",
      ["what is inflation", "why does inflation matter for savings", "what is real return", "does my fd beat inflation"],
      ("Inflation is the rise in prices over time. If your money earns less than prices rise, it buys less each year even though the number in the account grows.",
       "महँगाई समय के साथ भावों का बढ़ना है। आपका पैसा भावों के बढ़ने से कम कमाए तो खाते की संख्या बढ़ने पर भी वह हर साल कम ख़रीद पाता है।"),
      (["Real return is roughly your return minus inflation, and after tax. An FD paying 7% when prices rise 6% grows your buying power by only about 1%, and less once the interest is taxed.",
        "That is why money kept for decades in a savings account loses value, and why long-term goals usually include some equity.",
        "Everyday inflation is not the same for everyone: education and medical costs have often risen faster than the headline figure.",
        "Plan a goal in future prices: ₹10 lakh of costs today is much more in 15 years."],
       ["असली रिटर्न मोटे तौर पर आपका रिटर्न घटा महँगाई है, और कर के बाद। प्रति वर्ष 7% देने वाली FD जब भाव 6% बढ़ें, तो आपकी ख़रीद-क्षमता सिर्फ़ लगभग 1% बढ़ाती है, और ब्याज पर कर लगने के बाद उससे भी कम।",
        "इसीलिए दशकों तक बचत खाते में पड़ा पैसा मूल्य खोता है, और लंबे लक्ष्यों में आम तौर पर कुछ इक्विटी रखी जाती है।",
        "रोज़मर्रा की महँगाई सबके लिए एक जैसी नहीं: शिक्षा और इलाज का ख़र्च अक्सर सुर्ख़ी वाले आँकड़े से तेज़ बढ़ा है।",
        "लक्ष्य की योजना भविष्य के भावों में बनाइए: आज के ₹10 लाख का ख़र्च 15 साल में कहीं ज़्यादा होगा।"]),
      ("Inflation varies by year and by what you buy. Use it as a way to check your plan, not a fixed number.", "महँगाई साल और ख़रीद के अनुसार बदलती है। इसे योजना जाँचने का तरीक़ा समझिए, कोई तय संख्या नहीं।"),
      [("Will 10000 a month reach 50 lakh in 15 years?", "10000 महीने की SIP से 15 साल में 50 लाख बनेंगे?")]),

    C("emergency_fund_basics", "Saving", r"\b(how (big|much|large)|what size)\b.{0,30}\b(emergency (fund|savings|money)|rainy day)\b|\bwhat('?s| is) (an )?emergency (fund|savings)\b|\bwhy (do i|should i) (need|keep|have) (an )?emergency\b|\bwhere (to|should i) (keep|park|put)\b.{0,25}\bemergency\b",
      ["what is an emergency fund", "how much emergency fund should I keep", "where should I keep my emergency money", "why do I need an emergency fund"],
      ("An emergency fund is money set aside only for shocks such as a job loss, illness or a big repair, so you never have to borrow at a high rate or sell investments at a bad time.",
       "इमरजेंसी फ़ंड वह पैसा है जो सिर्फ़ झटकों के लिए अलग रखा जाता है, जैसे नौकरी जाना, बीमारी या बड़ी मरम्मत, ताकि आपको ऊँचे ब्याज पर उधार न लेना पड़े या बुरे समय पर निवेश न बेचना पड़े।"),
      (["A common rule of thumb is 6 months of essential expenses; 3 months if your income is very steady, 9 to 12 if it is irregular, you are self-employed, or others depend on you.",
        "Count only what you must pay: rent or EMI, food, bills, insurance premiums, school fees.",
        "Keep it where it is safe and quick to reach: a savings account, a sweep-in FD or a liquid fund. Not in shares, and not locked for years.",
        "Build it before you invest for goals. It is also what lets you stay invested through a crash instead of selling in panic.",
        "Use it only for real emergencies, then refill it."],
       ["आम अंगूठे का नियम 6 महीने के ज़रूरी ख़र्च हैं; आय बहुत स्थिर हो तो 3 महीने, अनियमित हो, आप स्वरोज़गार में हों या दूसरे आप पर निर्भर हों तो 9 से 12 महीने।",
        "सिर्फ़ वही गिनिए जो चुकाना ही है: किराया या EMI, खाना, बिल, बीमा प्रीमियम, स्कूल फ़ीस।",
        "इसे वहाँ रखिए जहाँ सुरक्षित और जल्दी मिले: बचत खाता, स्वीप-इन FD या लिक्विड फ़ंड। शेयरों में नहीं, और सालों के लिए बंद भी नहीं।",
        "लक्ष्यों के लिए निवेश से पहले इसे बनाइए। इसी से आप गिरावट में घबराकर बेचने की जगह टिके रह पाते हैं।",
        "सिर्फ़ असली आपात में इस्तेमाल कीजिए, फिर दोबारा भर दीजिए।"]),
      ("A rule of thumb, not a law. Your own figure depends on your costs and how steady your income is.", "यह अंगूठे का नियम है, क़ानून नहीं। आपकी अपनी रक़म आपके ख़र्च और आय की स्थिरता पर टिकी है।"),
      [("How long will 3 lakh last if I spend 40000 a month?", "3 लाख रुपये 40000 महीने के ख़र्च पर कितना चलेंगे?")],
      tool=("practice", "Measure your cushion", "अपनी गद्दी नापिए", {"tool": "emergency"}), tour="emergency"),

    C("start_investing", "Investing basics", r"\b(how (do|can|should) (i|we|one)|where (do|should) i|what('?s| is) the best way to|ways? to)\b.{0,25}\b(start|begin|get started)\b.{0,25}\b(invest\w*|saving|stock market|mutual funds?|sip)\b|\b(beginner|first[- ]time|new to)\b.{0,25}\b(invest\w*|stock market|mutual funds?)\b|\bstart investing\b|\bi am (a )?(beginner|new)\b|\bhow (do|can|to) (i )?(become|get|be|grow) (rich|wealthy|a millionaire|a crorepati)\b|\bbuild (long[- ]term )?wealth\b|\bget rich\b|\bfinancial freedom\b|\bgrow my (money|wealth|savings)\b",
      ["how do I start investing", "I am a beginner where do I begin investing", "first time investor what should I do", "how to start a sip with a small amount"],
      ("Start in this order: protect first, then invest steadily and cheaply. Doing the first steps well matters more than picking the perfect investment.",
       "इस क्रम में शुरू कीजिए: पहले सुरक्षा, फिर लगातार और सस्ते में निवेश। पहले क़दम ठीक से करना सबसे सही निवेश चुनने से ज़्यादा मायने रखता है।"),
      (["1. Emergency fund: about 6 months of expenses in savings or a liquid fund.",
        "2. Insurance: a pure term life policy if others depend on your income, and health insurance. Do not mix insurance with investing.",
        "3. Clear expensive debt: card balances and loans above about 12 to 15% a year cost more than most investments earn.",
        "4. KYC and a bank account linked to Aadhaar and PAN: the one-time paperwork for investing.",
        "5. Start a SIP (many funds accept ₹100 to ₹500 a month) in a low-cost index or diversified fund for goals 5 years or more away.",
        "6. Increase the SIP when income rises, ignore the daily noise, and review once or twice a year."],
       ["1. इमरजेंसी फ़ंड: बचत या लिक्विड फ़ंड में लगभग 6 महीने का ख़र्च।",
        "2. बीमा: जिन पर आपकी आय निर्भर है उनके लिए शुद्ध टर्म जीवन बीमा, और स्वास्थ्य बीमा। बीमा को निवेश से न मिलाइए।",
        "3. महँगा क़र्ज़ चुकाइए: कार्ड का बकाया और लगभग 12 से 15% सालाना से ऊपर के क़र्ज़ ज़्यादातर निवेशों की कमाई से महँगे पड़ते हैं।",
        "4. KYC और आधार-पैन से जुड़ा बैंक खाता: निवेश का एक बार का काग़ज़ी काम।",
        "5. 5 साल या ज़्यादा दूर के लक्ष्यों के लिए कम फ़ीस वाले इंडेक्स या विविध फ़ंड में SIP शुरू कीजिए (कई फ़ंड ₹100 से ₹500 महीने से मान लेते हैं)।",
        "6. आय बढ़े तो SIP बढ़ाइए, रोज़ के शोर को अनदेखा कीजिए और साल में एक-दो बार समीक्षा कीजिए।"]),
      ("Ignore anyone promising fixed or high returns, or pushing you to move fast. That is the shape of most scams.", "जो कोई पक्के या ऊँचे रिटर्न का वादा करे या जल्दी करने को कहे, उसे अनदेखा कीजिए। ज़्यादातर ठगी ऐसी ही होती है।"),
      [("Will 10000 a month reach 50 lakh in 15 years?", "10000 महीने की SIP से 15 साल में 50 लाख बनेंगे?"), ("Someone asked for my OTP on a call", "किसी ने फ़ोन पर मेरा OTP माँगा")],
      tool=("learn", "Try a SIP goal", "SIP लक्ष्य आज़माइए", {})),

    C("kyc_demat", "Investing basics", r"\b(demat|trading account|open (a |an )?(demat|trading|investment|mutual fund) account|kyc)\b.{0,30}\b(how|open|need|what|required|documents|process|steps)\b|\b(how|what).{0,25}\b(demat|kyc)\b",
      ["how do I open a demat account", "what is kyc for mutual funds", "what documents do I need to start investing", "do I need a demat account for mutual funds"],
      ("To invest you need a one-time identity check called KYC and, for shares and ETFs, a demat account. Mutual funds do not need a demat account.",
       "निवेश के लिए एक बार की पहचान जाँच (KYC) चाहिए और शेयर व ETF के लिए डीमैट खाता। म्यूचुअल फ़ंड के लिए डीमैट खाता ज़रूरी नहीं।"),
      (["KYC: PAN, Aadhaar (or another address proof), a photo and a bank account. Done online by video or OTP in a few minutes, and valid across funds.",
        "Demat account: holds shares in electronic form. Open it with a SEBI-registered broker; check the broker on SEBI's website before you start.",
        "Mutual funds: invest directly with the fund house or an app after KYC; no demat needed.",
        "Never share your OTP, PIN or demat login, and never let anyone 'operate' your account for you.",
        "Watch the charges: account opening, yearly maintenance and per-trade fees differ between brokers."],
       ["KYC: PAN, आधार (या दूसरा पते का प्रमाण), फ़ोटो और बैंक खाता। वीडियो या OTP से कुछ मिनट में ऑनलाइन हो जाता है और सभी फ़ंड में मान्य रहता है।",
        "डीमैट खाता: शेयर इलेक्ट्रॉनिक रूप में रखता है। इसे SEBI-पंजीकृत ब्रोकर से खोलिए; शुरू करने से पहले ब्रोकर को SEBI की वेबसाइट पर जाँच लीजिए।",
        "म्यूचुअल फ़ंड: KYC के बाद फ़ंड कंपनी या किसी ऐप से सीधे निवेश कीजिए; डीमैट नहीं चाहिए।",
        "अपना OTP, पिन या डीमैट लॉगिन कभी साझा न कीजिए, और किसी को अपना खाता 'चलाने' न दीजिए।",
        "शुल्क देखिए: खाता खोलने, सालाना रखरखाव और प्रति-ट्रेड फ़ीस ब्रोकर के हिसाब से अलग होती है।"]),
      ("Requirements and charges change, so confirm them with the broker or fund house.", "आवश्यकताएँ और शुल्क बदलते रहते हैं, इसलिए ब्रोकर या फ़ंड कंपनी से पुष्टि कर लीजिए।"),
      [("Someone asked for my OTP on a call", "किसी ने फ़ोन पर मेरा OTP माँगा")]),

    C("tax_basics", "Tax", r"\b(tax)\b.{0,40}\b(mutual funds?|equity|shares?|stocks?|gains?|fd|fixed deposit|investments?|sip|elss|debt funds?|interest)\b|\b(fd|fixed deposit|interest|mutual funds?)\b.{0,30}\btax\b|\b(capital gains?|ltcg|stcg|80c|section 80c|tax saving|save tax|elss)\b|\bhow (is|are)\b.{0,20}\b(taxed|taxation)\b",
      ["how are mutual funds taxed", "what is ltcg and stcg", "how to save tax by investing", "what is section 80c", "is fd interest taxable"],
      ("In India, tax on investments depends on what you hold and for how long. Equity held more than a year gets a lower long-term rate; selling sooner is taxed higher; fixed deposit interest is taxed at your income-tax slab.",
       "भारत में निवेश पर कर इस पर निर्भर है कि आप क्या रखते हैं और कितने समय। एक साल से ज़्यादा रखी इक्विटी पर कम दीर्घकालिक दर लगती है; जल्दी बेचने पर ज़्यादा; और फ़िक्स्ड डिपॉज़िट का ब्याज आपके आयकर स्लैब पर कर पाता है।"),
      (["Listed shares and equity mutual funds (as of the rules from July 2024): sold within 1 year, short-term gain taxed at 20%; sold after 1 year, long-term gain taxed at 12.5% on the part above ₹1.25 lakh gains in a year.",
        "Fixed deposit and savings interest is added to your income and taxed at your slab; banks cut TDS above a yearly threshold unless you give Form 15G/15H where eligible.",
        "Debt mutual funds bought now are generally taxed at your slab on the gain, whatever the holding period.",
        "Section 80C (old tax regime) lets you deduct up to ₹1.5 lakh a year for things like ELSS funds, PPF, EPF and life-insurance premiums. ELSS has a 3-year lock-in.",
        "Holding a profitable share past its one-year mark can cut the tax on it, which is what the Tax Shield tool shows for each of your holdings."],
       ["सूचीबद्ध शेयर और इक्विटी म्यूचुअल फ़ंड (जुलाई 2024 के नियमों के अनुसार): 1 साल के भीतर बेचने पर अल्पकालिक लाभ पर 20%; 1 साल के बाद बेचने पर दीर्घकालिक लाभ पर साल के ₹1.25 लाख लाभ से ऊपर के हिस्से पर 12.5%।",
        "फ़िक्स्ड डिपॉज़िट और बचत का ब्याज आपकी आय में जुड़कर आपके स्लैब पर कर पाता है; सालाना सीमा से ऊपर बैंक TDS काटते हैं, जब तक आप पात्र होने पर फ़ॉर्म 15G/15H न दें।",
        "अभी ख़रीदे डेट म्यूचुअल फ़ंड के लाभ पर आम तौर पर रखने की अवधि कुछ भी हो, आपके स्लैब के हिसाब से कर लगता है।",
        "धारा 80C (पुरानी कर व्यवस्था) ELSS फ़ंड, PPF, EPF और जीवन बीमा प्रीमियम जैसी चीज़ों पर साल का ₹1.5 लाख तक की कटौती देती है। ELSS में 3 साल का लॉक-इन है।",
        "मुनाफ़े वाले शेयर को एक साल के निशान से आगे रखने पर उस पर कर घट सकता है, जो टैक्स बचत औज़ार आपके हर शेयर के लिए दिखाता है।"]),
      ("Tax rates and limits are changed by each Budget. Treat these as the rules at the time of writing and confirm with the Income Tax website or a chartered accountant before acting.",
       "कर की दरें और सीमाएँ हर बजट में बदलती हैं। इन्हें लिखे जाने के समय के नियम समझिए और कुछ करने से पहले आयकर वेबसाइट या चार्टर्ड अकाउंटेंट से पुष्टि कर लीजिए।"),
      [("What if I sell Infosys today?", "आज Infosys बेचूँ तो क्या होगा?")],
      table={"columns": {"en": ["What", "Sold within 1 year", "Sold after 1 year"], "hi": ["क्या", "1 साल के भीतर", "1 साल के बाद"]},
             "rows": {"en": [["Shares / equity funds", "20% on gain", "12.5% on gain above ₹1.25 lakh a year"], ["FD interest", "Your slab", "Your slab"], ["Debt funds (new)", "Your slab", "Your slab"]],
                      "hi": [["शेयर / इक्विटी फ़ंड", "लाभ पर 20%", "साल के ₹1.25 लाख से ऊपर के लाभ पर 12.5%"], ["FD ब्याज", "आपका स्लैब", "आपका स्लैब"], ["डेट फ़ंड (नए)", "आपका स्लैब", "आपका स्लैब"]]}},
      tool=("protect", "Open the Tax Shield", "टैक्स बचत खोलिए", {"tool": "tax"}), tour="tax"),

    C("ppf_vs_nps", "Saving", r"\b(ppf|public provident fund)\b.{0,30}\b(nps|national pension|epf)\b|\b(nps|national pension)\b.{0,30}\b(ppf|public provident)\b|\bdifference between (ppf|nps)\b|\bwhat is (nps|ppf)\b",
      ["difference between nps and ppf", "ppf or nps which is better", "what is nps", "what is ppf"],
      ("PPF is a fixed, tax-free savings account for 15 years, safe and easy to understand. NPS is a pension account that mixes shares and bonds, and is locked until retirement.",
       "PPF एक तय, कर-मुक्त बचत खाता है (15 साल), सुरक्षित और समझने में आसान। NPS एक पेंशन खाता है जिसमें शेयर और बॉन्ड का मिश्रण होता है, और रिटायरमेंट तक बंद रहता है।"),
      (["PPF: government-set interest (reviewed every quarter), tax-free at every step, up to Rs 1.5 lakh a year, partial withdrawal after a few years.",
        "NPS: you choose the mix of equity and debt, gets extra tax deduction under the old regime, and at retirement part of the money must buy a pension (annuity).",
        "Choose PPF for a safe, fixed core. Choose NPS for long-term retirement money where you accept some market swings.",
        "Both lock your money for years, so do not put money you may need soon into either."],
       ["PPF: सरकार द्वारा तय ब्याज (हर तिमाही समीक्षा), हर चरण पर कर-मुक्त, सालाना ₹1.5 लाख तक, कुछ साल बाद आंशिक निकासी।",
        "NPS: इक्विटी और डेट का मिश्रण आप चुनते हैं, पुरानी कर व्यवस्था में अतिरिक्त कटौती, और रिटायरमेंट पर कुछ पैसे से पेंशन (एन्युइटी) लेनी होती है।",
        "सुरक्षित, तय हिस्से के लिए PPF। कुछ उतार-चढ़ाव स्वीकार करके लंबी अवधि के रिटायरमेंट पैसे के लिए NPS।",
        "दोनों सालों के लिए पैसा बंद करते हैं, इसलिए जिसकी जल्दी ज़रूरत हो, उसे दोनों में न डालें।"]),
      ("Rates and rules are set by the government and change; check the current figures on the PPF or NPS site before deciding.",
       "दरें और नियम सरकार तय करती है और बदलते हैं; फ़ैसले से पहले PPF या NPS की साइट पर ताज़ा आँकड़े देखिए।"),
      [("Which government schemes can I get?", "मुझे कौन सी सरकारी योजनाएँ मिल सकती हैं?")]),
    C("govt_savings", "Saving", r"\b(ppf|public provident fund|nps|national pension|epf|provident fund|sukanya|ssy|senior citizen savings|scss|post office (scheme|savings|fd|deposit)|nsc)\b",
      ["what is ppf", "what is nps", "ppf vs nps vs epf", "is sukanya samriddhi good", "post office savings schemes"],
      ("These are government-backed savings routes for the long term. They are safe, tax-friendly in different ways, and limited in how freely you can take the money out.",
       "ये दीर्घकालिक सरकार-समर्थित बचत के रास्ते हैं। ये सुरक्षित हैं, अलग-अलग तरह से कर-अनुकूल हैं, और पैसा कितनी आज़ादी से निकाल सकते हैं इसमें सीमित हैं।"),
      (["PPF: a 15-year account at a government-set rate that is reviewed every quarter; interest is tax-free; deposits up to ₹1.5 lakh a year; partial withdrawal only after a few years.",
        "EPF: for salaried employees, a share of salary goes in from you and your employer; meant for retirement; withdrawals are restricted.",
        "NPS: a pension account with a mix of equity and debt that you choose; part of the money must buy an annuity at retirement; extra tax deduction is available under the old regime.",
        "Sukanya Samriddhi: for a girl child's education and marriage; a government-set rate and tax benefits; locked until the child is much older.",
        "Senior Citizens' Savings Scheme and post-office deposits: fixed-rate options for steady income; the rate is set by the government and changes.",
        "The safe return is usually modest. These suit the 'safe core' of your money, not all of it."],
       ["PPF: 15 साल का खाता, सरकार द्वारा तय दर पर जो हर तिमाही समीक्षित होती है; ब्याज कर-मुक्त; साल का ₹1.5 लाख तक जमा; कुछ साल बाद ही आंशिक निकासी।",
        "EPF: वेतनभोगियों के लिए, वेतन का हिस्सा आप और आपके नियोक्ता डालते हैं; रिटायरमेंट के लिए; निकासी पर पाबंदी।",
        "NPS: पेंशन खाता जिसमें इक्विटी और डेट का मिश्रण आप चुनते हैं; रिटायरमेंट पर कुछ पैसे से एन्युइटी लेनी होती है; पुरानी व्यवस्था में अतिरिक्त कर कटौती उपलब्ध।",
        "सुकन्या समृद्धि: बालिका की शिक्षा और विवाह के लिए; सरकार तय दर और कर लाभ; बच्ची के काफ़ी बड़े होने तक बंद।",
        "वरिष्ठ नागरिक बचत योजना और डाकघर जमा: स्थिर आय के लिए तय दर के विकल्प; दर सरकार तय करती है और बदलती है।",
        "सुरक्षित रिटर्न आम तौर पर सामान्य होता है। ये आपके पैसे के 'सुरक्षित केंद्र' के लिए ठीक हैं, सारे के लिए नहीं।"]),
      ("Rates and limits are reset by the government, so check the current figures on India Post, the PPF/NPS portals or your bank before deciding.", "दरें और सीमाएँ सरकार बदलती है, इसलिए फ़ैसले से पहले इंडिया पोस्ट, PPF/NPS पोर्टल या अपने बैंक पर ताज़ा आँकड़े देखिए।"),
      [("Which government schemes can I get?", "मुझे कौन सी सरकारी योजनाएँ मिल सकती हैं?")],
      tool=("rural", "Check your schemes", "अपनी योजनाएँ जाँचिए", {})),

    C("market_falls", "Investing basics", r"\b(market|stocks?|portfolio|my (investments|shares)|nifty|sensex)\b.{0,25}\b(fall\w*|crash\w*|drop\w*|down|decline\w*|correction|bear)\b.{0,40}\b(what|should|do)\b|\bwhat (should|do|to) (i|we) do\b.{0,30}\b(market|stocks?|shares)\b.{0,15}\b(fall\w*|crash\w*|drop\w*|down)\b|\b(market|stocks?)\b.{0,15}\b(falls?|falling|crash\w*|drops?|dropping)\b.{0,20}\bwhat (should|do|to)\b|\b(market|stocks?) (is|are) (falling|crashing|down)\b|\bshould i (panic|worry|sell)\b.{0,40}\b(fall|crash|drop|down)\b",
      ["what should I do when the market falls", "the market is crashing should I worry", "my portfolio is down what to do", "is a market correction normal"],
      ("Falls are a normal part of owning equity: broad markets have often dropped 10% every year or two and 30% or more a few times a decade, and have recovered over long periods. What hurts most is selling at the bottom.",
       "गिरावट इक्विटी रखने का सामान्य हिस्सा है: बड़े बाज़ार अक्सर साल-दो साल में 10% गिरे हैं और दशक में कुछ बार 30% या ज़्यादा, और लंबे समय में सँभले हैं। सबसे ज़्यादा नुक़सान तली पर बेचने से होता है।"),
      (["First check: do you need this money within about 3 years? If yes, that money should not have been in equity, and the fix is to plan the exit, not to panic today.",
        "If your goal is far away, a fall usually means the same SIP buys more units at lower prices.",
        "Do not decide in a day of headlines. Write your rule in advance (for example, 'I will rebalance when equity moves 5 points from target').",
        "Check that you are not over-concentrated: a fall in one sector hurts a concentrated portfolio far more.",
        "Keep your emergency fund separate so you never have to sell during a fall.",
        "Past recoveries do not guarantee future ones: some markets and companies have taken many years or never come back, which is why spread matters."],
       ["पहले जाँचिए: क्या इस पैसे की लगभग 3 साल में ज़रूरत है? है, तो वह पैसा इक्विटी में नहीं होना था, और हल आज घबराना नहीं बल्कि निकलने की योजना बनाना है।",
        "लक्ष्य दूर हो तो गिरावट का मतलब आम तौर पर यह है कि वही SIP सस्ते भाव पर ज़्यादा यूनिट ख़रीदती है।",
        "सुर्ख़ियों वाले एक दिन में फ़ैसला न कीजिए। नियम पहले से लिख लीजिए (जैसे 'इक्विटी लक्ष्य से 5 अंक हिले तो संतुलन करूँगा')।",
        "जाँचिए कि आप ज़्यादा केंद्रित तो नहीं: एक सेक्टर की गिरावट केंद्रित पोर्टफ़ोलियो को कहीं ज़्यादा चोट देती है।",
        "इमरजेंसी फ़ंड अलग रखिए ताकि गिरावट में बेचना न पड़े।",
        "पिछली वापसी भविष्य की गारंटी नहीं: कुछ बाज़ार और कंपनियाँ सँभलने में कई साल लगा चुके हैं या कभी नहीं सँभलीं, इसीलिए फैलाव मायने रखता है।"]),
      ("I cannot tell you where the market goes next. Nobody can.", "बाज़ार आगे कहाँ जाएगा, यह मैं नहीं बता सकता। कोई नहीं बता सकता।"),
      [("What if I had sold during the Covid crash?", "कोविड गिरावट में बेच देता तो क्या होता?"), ("What if the market drops 20%?", "बाज़ार 20% गिरे तो क्या होगा?")],
      tool=("protect", "Replay a past crash", "पिछली गिरावट का रिप्ले", {"tool": "panic"}), tour="panic"),

    C("fundamentals_technicals", "Stocks", r"\b(fundamental|technical)\b.{0,30}\b(analysis|analyses|indicators?|vs|versus|and|or|mean|means)\b|\b(what (are|is)|explain)\b.{0,15}\b(fundamentals?|technicals?|technical analysis|fundamental analysis|moving average|rsi|support and resistance)\b|\bhow (do|to) (i )?(analy[sz]e|evaluate|pick|choose|research|select)\b.{0,20}\b(a )?(stock|share|company)\b|\bhow to read a (stock|company)\b",
      ["what is fundamental analysis", "what is technical analysis", "how do I analyse a stock", "how to evaluate a company before investing", "what is rsi and moving average"],
      ("Fundamentals ask 'is this a good business and is the price fair?'. Technicals ask 'what has the price been doing?'. Fundamentals suit deciding what to own; technicals describe the recent mood and timing, and predict nothing.",
       "फ़ंडामेंटल पूछते हैं 'क्या यह अच्छा कारोबार है और क्या भाव वाजिब है?'। टेक्निकल पूछते हैं 'भाव अभी क्या कर रहा है?'। फ़ंडामेंटल यह तय करने में काम आते हैं कि क्या रखा जाए; टेक्निकल हाल का मिज़ाज और समय बताते हैं, भविष्यवाणी नहीं करते।"),
      (["Growth: are sales and profit rising year after year?",
        "Profitability: return on equity (profit per ₹1 of shareholders' money) and margin (profit per ₹1 of sales).",
        "Cash: does profit turn into cash (operating cash flow compared with profit), and is free cash left after investing?",
        "Safety: debt compared with equity, and how many times profit covers the interest bill.",
        "Price: P/E (price per ₹1 of yearly profit), compared with similar companies and the company's own past.",
        "Technicals: the 50-day and 200-day average (trend), RSI (how stretched a recent move is), volume (how heavy the trading is) and distance from the year's high or low.",
        "No single number decides. Read several together and keep in mind what the data cannot see, such as management quality and the future."],
       ["बढ़त: क्या बिक्री और मुनाफ़ा साल-दर-साल बढ़ रहे हैं?",
        "मुनाफ़ा देने की क्षमता: रिटर्न ऑन इक्विटी (शेयरधारकों के हर ₹1 पर मुनाफ़ा) और मार्जिन (बिक्री के हर ₹1 पर मुनाफ़ा)।",
        "नक़दी: क्या मुनाफ़ा नक़द बनता है (ऑपरेटिंग कैश फ़्लो बनाम मुनाफ़ा), और निवेश के बाद फ़्री कैश बचता है?",
        "सुरक्षा: क़र्ज़ बनाम इक्विटी, और मुनाफ़ा ब्याज के बिल को कितनी बार ढकता है।",
        "भाव: P/E (सालाना मुनाफ़े के हर ₹1 का भाव), समान कंपनियों और कंपनी के अपने अतीत से तुलना में।",
        "टेक्निकल: 50-दिन और 200-दिन का औसत (रुझान), RSI (हाल की चाल कितनी खिंची है), वॉल्यूम (कारोबार कितना भारी है) और साल के ऊँचे या नीचे से दूरी।",
        "कोई एक संख्या फ़ैसला नहीं करती। कई को साथ पढ़िए और याद रखिए कि डेटा क्या नहीं देख पाता, जैसे प्रबंधन की गुणवत्ता और भविष्य।"]),
      ("The Research page does exactly this for any listed company and marks how much to trust each point.", "शोध पेज किसी भी सूचीबद्ध कंपनी के लिए ठीक यही करता है और हर बात पर कितना भरोसा करें यह दिखाता है।"),
      [("Analyse TCS", "TCS का विश्लेषण कीजिए"), ("Compare Reliance and HDFC Bank", "Reliance और HDFC Bank की तुलना कीजिए")],
      tool=("research", "Open the Research page", "शोध पेज खोलिए", {}), tour="research"),

    C("pe_ratio", "Stocks", r"\b(p/?e|price[- ]to[- ]earnings?|price earnings|pe ratio|eps|earnings per share|market cap(italisation|italization)?|roe|return on equity|book value|p/?b ratio|dividend yield|ebitda|debt to equity|free cash flow|peg ratio)\b.{0,30}\b(mean|means|what|why|how|good|high|low|explain|calculate)\b|\bwhat('?s| is| does)\b.{0,12}\b(p/?e|pe ratio|eps|roe|market cap|dividend yield|book value|ebitda|free cash flow|peg)\b",
      ["what is pe ratio", "what does market cap mean", "what is eps", "what is roe", "what is dividend yield", "what is free cash flow"],
      ("These are the standard yardsticks for a company. Each answers one narrow question, so use them together and always compare a company with similar ones, not with all companies.",
       "ये किसी कंपनी को नापने के मानक पैमाने हैं। हर एक एक संकरे सवाल का जवाब देता है, इसलिए उन्हें साथ में इस्तेमाल कीजिए और कंपनी की तुलना सभी कंपनियों से नहीं, समान कंपनियों से कीजिए।"),
      (["P/E (price to earnings): the share price divided by yearly profit per share. P/E 20 means you pay ₹20 for each ₹1 of yearly profit. High can mean growth is expected, or that it is expensive.",
        "EPS (earnings per share): the company's profit divided by the number of shares.",
        "Market cap: share price times number of shares, the market's price for the whole company. It tells you size, not value.",
        "ROE (return on equity): yearly profit as a share of shareholders' money. Above about 15% is often called good, but compare within the industry.",
        "Dividend yield: yearly dividend divided by the share price. A very high yield can be a warning that the price has fallen or the payout is unsustainable.",
        "Free cash flow: the cash left after running the business and investing in it. It is what can really be paid out or used to cut debt.",
        "PEG: P/E divided by the profit growth rate in percent. Under about 1 means you pay little for the growth, over about 2.5 a lot, if the growth lasts."],
       ["P/E (भाव बनाम कमाई): शेयर का भाव भाग प्रति शेयर सालाना मुनाफ़ा। P/E 20 का मतलब सालाना मुनाफ़े के हर ₹1 के लिए ₹20 देना। ऊँचे का मतलब बढ़त की उम्मीद हो सकती है, या कि महँगा है।",
        "EPS (प्रति शेयर कमाई): कंपनी का मुनाफ़ा भाग शेयरों की संख्या।",
        "मार्केट कैप: शेयर का भाव गुणा शेयरों की संख्या, पूरी कंपनी का बाज़ार भाव। यह आकार बताता है, मूल्य नहीं।",
        "ROE (रिटर्न ऑन इक्विटी): सालाना मुनाफ़ा शेयरधारकों के पैसे के हिस्से के रूप में। लगभग 15% से ऊपर को अक्सर अच्छा कहते हैं, पर तुलना अपने उद्योग में कीजिए।",
        "डिविडेंड यील्ड: सालाना डिविडेंड भाग शेयर का भाव। बहुत ऊँची यील्ड चेतावनी हो सकती है कि भाव गिरा है या भुगतान टिकाऊ नहीं।",
        "फ़्री कैश फ़्लो: कारोबार चलाने और उसमें निवेश के बाद बची नक़दी। इसी से असल में भुगतान या क़र्ज़ घटाना हो सकता है।",
        "PEG: P/E भाग मुनाफ़े की बढ़त दर (प्रतिशत में)। लगभग 1 से कम का मतलब बढ़त के लिए कम देना, लगभग 2.5 से ऊपर का ज़्यादा, अगर बढ़त टिके।"]),
      ("A number alone is not a verdict. A low P/E can signal a problem and a high P/E can be deserved.", "अकेली संख्या फ़ैसला नहीं होती। कम P/E किसी समस्या का संकेत हो सकता है और ऊँचा P/E जायज़ भी।"),
      [("Analyse TCS", "TCS का विश्लेषण कीजिए"), ("Compare Infosys and Wipro", "Infosys और Wipro की तुलना कीजिए")],
      tool=("research", "See these for a company", "किसी कंपनी के लिए देखिए", {})),

    C("cap_sizes", "Stocks", r"\b(large|mid|small|micro|flexi|multi)[- ]?cap\b.{0,30}\b(what|difference|vs|versus|risk|risky|safe|better|mean|means|explain)\b|\bwhat (are|is) (large|mid|small)[- ]?cap\b|\b(large|mid|small) cap (vs|versus|or)\b",
      ["what is the difference between large cap mid cap and small cap", "are small cap funds risky", "what is a flexi cap fund"],
      ("'Cap' is the size of the company by market value. In India, SEBI ranks listed companies: the top 100 are large-cap, the next 150 mid-cap and the rest small-cap. Smaller means more growth potential and more swings.",
       "'कैप' कंपनी का बाज़ार मूल्य के हिसाब से आकार है। भारत में SEBI सूचीबद्ध कंपनियों को क्रम देता है: शीर्ष 100 लार्ज-कैप, अगली 150 मिड-कैप और बाक़ी स्मॉल-कैप। जितनी छोटी, उतनी ज़्यादा बढ़त की संभावना और उतने ज़्यादा झटके।"),
      (["Large-cap: established companies; usually steadier; falls are generally milder; growth is often slower.",
        "Mid-cap: faster-growing but more volatile; they can fall sharply in a bad market.",
        "Small-cap: highest potential and highest risk; can be hard to sell quickly and can stay down for years.",
        "Flexi-cap and multi-cap funds let the manager (or rules) spread across sizes.",
        "A longer horizon (7 years or more) and a smaller share of your money are the usual conditions for taking small-cap risk."],
       ["लार्ज-कैप: जमी हुई कंपनियाँ; आम तौर पर स्थिर; गिरावट प्रायः हल्की; बढ़त अक्सर धीमी।",
        "मिड-कैप: तेज़ बढ़त पर ज़्यादा उतार-चढ़ाव; ख़राब बाज़ार में तेज़ गिर सकती हैं।",
        "स्मॉल-कैप: सबसे ज़्यादा संभावना और सबसे ज़्यादा जोखिम; जल्दी बेचना कठिन हो सकता है और सालों नीचे रह सकती हैं।",
        "फ़्लेक्सी-कैप और मल्टी-कैप फ़ंड में मैनेजर (या नियम) आकारों में फैलाता है।",
        "लंबी अवधि (7 साल या ज़्यादा) और आपके पैसे का छोटा हिस्सा, स्मॉल-कैप जोखिम लेने की आम शर्तें हैं।"]),
      ("The cut-offs are reviewed every six months, so a company can move between groups.", "सीमाएँ हर छह महीने पर समीक्षित होती हैं, इसलिए कंपनी एक समूह से दूसरे में जा सकती है।"),
      [("Am I diversified?", "क्या मेरा पैसा अलग-अलग जगह बँटा है?")]),

    C("risk_profile", "Investing basics", r"\b(risk (profile|appetite|tolerance|capacity)|how (much )?risk\b|am i (a )?(conservative|aggressive|moderate)|what is my risk|risky or safe)\b|\b(safe|safest|risky|risk[- ]free)\b.{0,25}\b(invest\w*|option|options|place|way)\b",
      ["what is my risk profile", "what is risk appetite", "what is the safest investment", "how much risk can I take"],
      ("Risk has two parts: how much loss you can afford (capacity) and how much loss you can sit through without panicking (tolerance). Your plan should respect the smaller of the two.",
       "जोखिम के दो हिस्से हैं: आप कितना नुक़सान सह सकते हैं (क्षमता) और घबराए बिना कितना नुक़सान झेल सकते हैं (सहनशीलता)। आपकी योजना दोनों में से छोटे का सम्मान करे।"),
      (["Capacity depends on your age, income stability, dependants, debts and when you need the money.",
        "Tolerance is about you: if a 20% fall would make you sell, a heavy equity share is not right for you however young you are.",
        "No investment is risk-free. Even a bank FD has the risk that interest lags inflation, and that a bank can fail beyond the ₹5 lakh deposit insurance cover per depositor per bank.",
        "Typical ordering from lower to higher risk: savings and FD, government schemes, debt funds, hybrid funds, large-cap equity, mid and small-cap equity, single stocks, crypto and options.",
        "A good test: imagine your investments down 30% for 18 months. What do you do? Your honest answer is your tolerance."],
       ["क्षमता आपकी उम्र, आय की स्थिरता, आश्रितों, क़र्ज़ों और पैसे की ज़रूरत के समय पर निर्भर है।",
        "सहनशीलता आपके बारे में है: 20% गिरावट आपको बेचने पर मजबूर करे तो भारी इक्विटी आपके लिए ठीक नहीं, चाहे आप कितने भी युवा हों।",
        "कोई निवेश जोखिम-मुक्त नहीं। बैंक FD में भी जोखिम है कि ब्याज महँगाई से पीछे रहे, और बैंक डूबे तो प्रति जमाकर्ता प्रति बैंक ₹5 लाख के जमा बीमा से ऊपर का पैसा जा सकता है।",
        "कम से ज़्यादा जोखिम का आम क्रम: बचत और FD, सरकारी योजनाएँ, डेट फ़ंड, हाइब्रिड फ़ंड, लार्ज-कैप इक्विटी, मिड और स्मॉल-कैप, अकेले शेयर, क्रिप्टो और ऑप्शन।",
        "अच्छी परीक्षा: कल्पना कीजिए आपका निवेश 18 महीने 30% नीचे है। आप क्या करेंगे? आपका ईमानदार जवाब ही आपकी सहनशीलता है।"]),
      ("Both capacity and tolerance can change with life events, so revisit them once a year.", "जीवन की घटनाओं से क्षमता और सहनशीलता दोनों बदल सकती हैं, इसलिए साल में एक बार दोबारा देखिए।"),
      [("What would a 30% crash do to my portfolio?", "30% गिरावट मेरे पोर्टफ़ोलियो का क्या करेगी?")],
      tool=("protect", "Replay a past crash", "पिछली गिरावट का रिप्ले", {"tool": "panic"})),

    C("rebalancing", "Investing basics", r"\brebalanc\w+\b.{0,30}\b(what|why|how|when|often|mean|means|portfolio)\b|\bwhat (is|does)\b.{0,10}\brebalanc\w+\b|\bhow often should i (review|rebalance)\b",
      ["what is rebalancing", "how often should I rebalance my portfolio", "why rebalance"],
      ("Rebalancing means bringing your mix back to its plan. When equities rise, they become a bigger share than you intended; you trim them (or direct new money elsewhere) to keep your risk where you chose it.",
       "रीबैलेंसिंग का मतलब अपने मिश्रण को योजना पर वापस लाना है। इक्विटी बढ़ने पर उसका हिस्सा आपकी मंशा से बड़ा हो जाता है; आप उसे घटाते हैं (या नया पैसा कहीं और डालते हैं) ताकि जोखिम वहीं रहे जहाँ आपने चुना था।"),
      (["Set a target mix first, for example 70% equity and 30% safe.", "Check once or twice a year, or when a share drifts more than about 5 percentage points from target.",
        "The cheapest way is to send new SIP money to the part that has fallen behind, which needs no selling and no tax.",
        "Selling can trigger tax, so use the Tax Shield to see what a sale would cost before you do it.",
        "In this app, the Rebalance tool builds the smallest set of trades that gets you back inside your own limits."],
       ["पहले लक्ष्य मिश्रण तय कीजिए, जैसे 70% इक्विटी और 30% सुरक्षित।", "साल में एक-दो बार जाँचिए, या जब कोई हिस्सा लक्ष्य से लगभग 5 प्रतिशत अंक से ज़्यादा खिसके।",
        "सबसे सस्ता तरीक़ा है नया SIP पैसा उस हिस्से में डालना जो पीछे रह गया, जिसमें बेचना और कर नहीं लगता।",
        "बेचने पर कर लग सकता है, इसलिए बेचने से पहले टैक्स बचत देखिए कि बिक्री की क़ीमत क्या होगी।",
        "इस ऐप में पुनर्संतुलन औज़ार सबसे छोटे ट्रेड बनाता है जो आपको अपनी सीमाओं के भीतर वापस ले आएँ।"]),
      ("Rebalancing does not raise returns by itself; it keeps risk where you want it.", "रीबैलेंसिंग अपने-आप रिटर्न नहीं बढ़ाती; यह जोखिम को वहाँ रखती है जहाँ आप चाहते हैं।"),
      [("What should I sell?", "मुझे क्या बेचना चाहिए?")],
      tool=("govern", "Open the rebalance simulator", "पुनर्संतुलन अनुकरण खोलिए", {}), tour="rebalance"),

    C("debt_funds", "Funds", r"\b(debt funds?|liquid funds?|bond funds?|gilt|hybrid funds?|balanced (advantage )?funds?|arbitrage funds?)\b|\bwhat (are|is) (a )?(debt|liquid|hybrid)\b",
      ["what is a debt fund", "what is a liquid fund", "what are hybrid funds", "are debt funds safe"],
      ("Debt funds lend money (to the government and to companies) and pass on the interest. They usually swing less than equity, but they are not guaranteed, unlike a bank FD.",
       "डेट फ़ंड (सरकार और कंपनियों को) पैसा उधार देते हैं और ब्याज आगे देते हैं। ये आम तौर पर इक्विटी से कम हिलते हैं, पर बैंक FD की तरह गारंटीशुदा नहीं हैं।"),
      (["Liquid funds: very short loans (up to 91 days); used to park emergency or near-term money; small swings.",
        "Short and ultra-short funds: a little longer; small changes in interest rates move the price slightly.",
        "Long-duration and gilt funds: rise when interest rates fall and fall when they rise, so they can swing a lot.",
        "Credit risk: funds that lend to weaker companies pay more and can lose money if a borrower defaults. Look at the fund's credit quality.",
        "Hybrid funds mix equity and debt in one product: a simple choice for a balanced mix. Gains on debt funds bought now are taxed at your slab."],
       ["लिक्विड फ़ंड: बहुत छोटी अवधि के उधार (91 दिन तक); इमरजेंसी या नज़दीकी पैसा टिकाने में काम आते हैं; हल्के उतार-चढ़ाव।",
        "शॉर्ट और अल्ट्रा-शॉर्ट फ़ंड: थोड़ी लंबी अवधि; ब्याज दरों में छोटे बदलाव से भाव थोड़ा हिलता है।",
        "लंबी अवधि और गिल्ट फ़ंड: ब्याज दर गिरने पर चढ़ते और बढ़ने पर गिरते हैं, इसलिए काफ़ी हिल सकते हैं।",
        "क्रेडिट जोखिम: कमज़ोर कंपनियों को उधार देने वाले फ़ंड ज़्यादा देते हैं और उधार लेने वाला चूके तो पैसा खो सकते हैं। फ़ंड की क्रेडिट गुणवत्ता देखिए।",
        "हाइब्रिड फ़ंड इक्विटी और डेट एक उत्पाद में मिलाते हैं: संतुलित मिश्रण का सरल चुनाव। अभी ख़रीदे डेट फ़ंड के लाभ पर आपके स्लैब के हिसाब से कर लगता है।"]),
      ("Not insured: only bank deposits have deposit insurance (up to ₹5 lakh per depositor per bank).", "बीमित नहीं: सिर्फ़ बैंक जमा पर जमा बीमा है (प्रति जमाकर्ता प्रति बैंक ₹5 लाख तक)।"),
      [("What does a 2% fee cost over 20 years?", "2% फ़ीस बीस साल में कितनी पड़ती है?")]),

    C("gold", "Investing basics", r"\b(gold|sgb|sovereign gold|gold etf|digital gold|silver)\b.{0,40}\b(invest\w*|buy|good|safe|worth|better|should|vs|best|return|returns|options?)\b|\binvest\w*\b.{0,15}\b(in )?(gold|silver)\b",
      ["should I invest in gold", "is gold a good investment", "sovereign gold bond vs gold etf", "digital gold safe or not"],
      ("Gold can be a small stabiliser: it often holds up when shares fall and keeps value against inflation over very long periods, but it pays no interest and can stay flat for years.",
       "सोना एक छोटा स्थिरक हो सकता है: शेयर गिरने पर अक्सर टिका रहता है और बहुत लंबे समय में महँगाई के सामने मूल्य बचाता है, पर कोई ब्याज नहीं देता और सालों सपाट रह सकता है।"),
      (["Common ways: gold ETFs and gold funds (regulated, easy to buy, no storage), sovereign gold bonds (government-issued, pay a small interest, long lock-in, tax benefit if held to maturity; new issues are rare), jewellery and coins (making charges and purity concerns), digital gold (check the provider's regulation: it is not under SEBI).",
        "A small share, often cited at around 5 to 10% of a portfolio, is a rule of thumb for diversification; it is not a target to chase.",
        "Jewellery is for wearing: its making charges are lost when you sell.",
        "Prices swing with global rates and the rupee, so do not buy gold at festival-time rush as a 'sure' investment."],
       ["आम तरीक़े: गोल्ड ETF और गोल्ड फ़ंड (नियंत्रित, ख़रीदना आसान, रखने का झंझट नहीं), सॉवरेन गोल्ड बॉन्ड (सरकार जारी करती है, थोड़ा ब्याज, लंबा लॉक-इन, परिपक्वता तक रखने पर कर लाभ; नए निर्गम कम आते हैं), गहने और सिक्के (मेकिंग चार्ज और शुद्धता की चिंता), डिजिटल गोल्ड (प्रदाता का नियमन देखिए: यह SEBI के अधीन नहीं)।",
        "छोटा हिस्सा, अक्सर पोर्टफ़ोलियो का लगभग 5 से 10%, विविधीकरण के लिए अंगूठे का नियम है; पीछा करने का लक्ष्य नहीं।",
        "गहने पहनने के लिए हैं: बेचते समय उनका मेकिंग चार्ज नहीं मिलता।",
        "भाव वैश्विक दरों और रुपये के साथ झूलते हैं, इसलिए त्योहार की भीड़ में सोना 'पक्के' निवेश के रूप में न ख़रीदिए।"]),
      ("Past gold returns do not promise future ones.", "सोने के पिछले रिटर्न आगे की गारंटी नहीं।"),
      [("Am I diversified?", "क्या मेरा पैसा अलग-अलग जगह बँटा है?")]),

    C("crypto", "Investing basics", r"\b(crypto\w*|bitcoin|btc|ethereum|nft|altcoins?|dogecoin)\b",
      ["should I invest in crypto", "is bitcoin safe", "how is crypto taxed in india"],
      ("Crypto is highly speculative: prices can fall 50% or more quickly, there is no company earnings behind most coins, and in India it is not regulated like shares or funds.",
       "क्रिप्टो बेहद सट्टे वाला है: भाव जल्दी 50% या ज़्यादा गिर सकते हैं, ज़्यादातर सिक्कों के पीछे किसी कंपनी की कमाई नहीं, और भारत में इसे शेयरों या फ़ंड की तरह नियंत्रित नहीं किया गया है।"),
      (["Tax in India: gains from virtual digital assets are taxed at a flat 30%, losses cannot be set off against other income, and 1% TDS applies on transfers above the threshold. (As of the rules at the time of writing.)",
        "Many frauds are dressed up as crypto: fake exchanges, 'guaranteed daily returns', and giveaways that need you to send coins first.",
        "If someone does hold it, it is usually kept to an amount whose total loss would not change their life, a small share of the portfolio.",
        "Never invest because a friend, a Telegram group or an influencer says it is about to rise."],
       ["भारत में कर: वर्चुअल डिजिटल एसेट से लाभ पर सपाट 30% कर, नुक़सान की दूसरी आय से भरपाई नहीं, और सीमा से ऊपर के ट्रांसफ़र पर 1% TDS। (लिखे जाने के समय के नियमों के अनुसार।)",
        "बहुत सी ठगी क्रिप्टो के नाम पर होती है: नक़ली एक्सचेंज, 'रोज़ का पक्का मुनाफ़ा' और गिवअवे जिनमें पहले सिक्के भेजने पड़ते हैं।",
        "जो रखते भी हैं, वे आम तौर पर इतनी रक़म रखते हैं जिसका पूरा नुक़सान उनकी ज़िंदगी न बदले, यानी पोर्टफ़ोलियो का छोटा हिस्सा।",
        "किसी दोस्त, टेलीग्राम समूह या इन्फ़्लुएंसर के कहने पर कि भाव बढ़ने वाला है, कभी निवेश न कीजिए।"]),
      ("I cannot tell you whether a coin will rise. Anyone who says they can is selling something.", "मैं नहीं बता सकता कि कोई सिक्का बढ़ेगा या नहीं। जो कहे कि बता सकता है, वह कुछ बेच रहा है।"),
      [("Is this tip real? Telegram group promises double money", "क्या यह टिप असली है? टेलीग्राम ग्रुप पैसा दुगना करने का वादा करता है")],
      tool=("protect", "Check a tip", "टिप जाँचिए", {"tool": "tip"}), tour="tip"),

    C("ipo", "Stocks", r"\b(ipo|initial public offering|listing gain|grey market premium|gmp|subscribe to (an )?ipo|apply (for|in) (an )?ipo)\b",
      ["what is an ipo", "should I apply for an ipo", "what is gmp in ipo", "how does ipo allotment work"],
      ("An IPO is when a company sells its shares to the public for the first time. You apply through your bank or broker; if too many people apply, allotment is by lottery, so you may get nothing or a small lot.",
       "IPO वह है जब कोई कंपनी पहली बार जनता को अपने शेयर बेचती है। आप बैंक या ब्रोकर से आवेदन करते हैं; बहुत लोग आवेदन करें तो आवंटन लॉटरी से होता है, इसलिए आपको कुछ नहीं या छोटा लॉट मिल सकता है।"),
      (["Read the company's prospectus (the 'RHP') for what it does, how it makes money, its debt and what the raised money is for.",
        "Price band and valuation: compare the P/E with listed peers, and check whether the sellers are the company (new money for growth) or early investors cashing out.",
        "GMP (grey market premium) is an unofficial, unregulated chatter number. It is not a forecast and not part of the issue.",
        "A listing-day gain is not guaranteed; plenty of IPOs list below their issue price.",
        "Apply only with money you do not need soon, and only from your own bank or broker's app. Anyone selling 'guaranteed allotment' is a fraud."],
       ["कंपनी का प्रॉस्पेक्टस ('RHP') पढ़िए: वह क्या करती है, कमाती कैसे है, उस पर कितना क़र्ज़ है और जुटाया पैसा किसलिए है।",
        "प्राइस बैंड और मूल्यांकन: P/E की तुलना सूचीबद्ध साथियों से कीजिए, और देखिए कि बेचने वाली कंपनी है (बढ़त के लिए नया पैसा) या शुरुआती निवेशक निकल रहे हैं।",
        "GMP (ग्रे मार्केट प्रीमियम) एक अनौपचारिक, अनियंत्रित चर्चा-संख्या है। यह पूर्वानुमान नहीं और निर्गम का हिस्सा नहीं।",
        "लिस्टिंग के दिन लाभ की गारंटी नहीं; बहुत से IPO निर्गम भाव से नीचे सूचीबद्ध होते हैं।",
        "सिर्फ़ ऐसे पैसे से आवेदन कीजिए जिसकी जल्दी ज़रूरत नहीं, और सिर्फ़ अपने बैंक या ब्रोकर के ऐप से। 'पक्का आवंटन' बेचने वाला हर व्यक्ति ठग है।"]),
      ("I cannot tell you whether a particular IPO will gain.", "मैं नहीं बता सकता कि कोई ख़ास IPO चढ़ेगा या नहीं।"),
      [("Check a stock tip", "स्टॉक टिप जाँचिए")]),

    C("term_vs_ulip", "Insurance", r"\b(term (insurance|plan|life)|ulip|endowment|money[- ]?back|whole life|life insurance|health insurance|mediclaim|insurance (or|vs|and) invest\w*|buy insurance)\b.{0,40}\b(what|which|good|bad|best|should|worth|vs|how much|need|difference|better)\b|\bhow much (life )?(insurance|cover)\b|\bdo i need (life |health )?insurance\b",
      ["what is term insurance", "term insurance vs endowment", "how much life cover do I need", "is ulip a good investment", "do i need health insurance"],
      ("Insurance is for protection, investing is for growth. Buying them separately is usually cheaper and clearer: a pure term plan for life cover and a health policy, and your investing in funds.",
       "बीमा सुरक्षा के लिए है, निवेश बढ़त के लिए। इन्हें अलग-अलग लेना आम तौर पर सस्ता और साफ़ होता है: जीवन कवर के लिए शुद्ध टर्म प्लान और एक स्वास्थ्य पॉलिसी, और निवेश फ़ंड में।"),
      (["Term insurance: a large cover for a low premium, paying your family if you die during the term. No maturity payout, and that is why it is cheap.",
        "A common rule of thumb for life cover is about 10 to 15 times your yearly income, adjusted for debts and how many people depend on you.",
        "Endowment, money-back and ULIPs mix insurance with saving: premiums are high, charges are heavy and the effective return is often low. Compare them to a term plan plus a fund before buying.",
        "Health insurance: buy it early, a family floater or individual covers, read the waiting periods, room-rent limits and exclusions. Employer cover alone ends when you leave the job.",
        "Never buy a policy because an agent says it is a 'limited-time' offer or returns 'double'. Check the claim settlement record and read the policy document."],
       ["टर्म बीमा: कम प्रीमियम पर बड़ा कवर, अवधि में मृत्यु होने पर आपके परिवार को भुगतान। परिपक्वता पर कोई भुगतान नहीं, और इसीलिए यह सस्ता है।",
        "जीवन कवर का आम अंगूठे का नियम आपकी सालाना आय का लगभग 10 से 15 गुना है, क़र्ज़ों और निर्भर लोगों की संख्या के हिसाब से समायोजित।",
        "एंडोमेंट, मनी-बैक और ULIP बीमा और बचत मिलाते हैं: प्रीमियम ऊँचा, शुल्क भारी और असली रिटर्न अक्सर कम। ख़रीदने से पहले इनकी तुलना टर्म प्लान और फ़ंड से कीजिए।",
        "स्वास्थ्य बीमा: जल्दी लीजिए, फ़ैमिली फ़्लोटर या अलग-अलग कवर, इंतज़ार की अवधि, कमरे के किराए की सीमा और अपवाद पढ़िए। सिर्फ़ नियोक्ता का कवर नौकरी छोड़ने पर ख़त्म हो जाता है।",
        "एजेंट के 'सीमित समय' या 'दुगना रिटर्न' कहने पर कोई पॉलिसी न ख़रीदिए। क्लेम सेटलमेंट रिकॉर्ड देखिए और पॉलिसी दस्तावेज़ पढ़िए।"]),
      ("For an agent-sold plan you already have, the Rural page's policy check estimates what it really returns.", "एजेंट से ली पॉलिसी हो तो ग्रामीण पेज की पॉलिसी जाँच बताती है कि उसका असली रिटर्न क्या बनता है।"),
      [("Is my LIC policy good? premium 50000 a year", "क्या मेरी LIC पॉलिसी अच्छी है?")],
      tool=("rural", "Check a policy", "पॉलिसी जाँचिए", {})),

    C("emi_loans", "Loans", r"\b(emi|equated monthly|home loan|personal loan|car loan|education loan|loan (interest|rate|tenure|prepay\w*)|prepay\w*|foreclos\w+|reducing balance|flat rate)\b.{0,40}\b(what|how|work|works|calculate|calculated|compare|better|should|vs|reduce|pay|save)\b|\bhow (is|are) (my )?emi\b|\bshould i prepay\b",
      ["how is emi calculated", "should I prepay my home loan", "flat rate vs reducing balance interest", "how to reduce loan interest"],
      ("Your EMI is a fixed monthly payment made of interest plus a part of the loan. At the start most of each EMI is interest; over time more of it repays the loan.",
       "आपकी EMI हर महीने की तय किस्त है जिसमें ब्याज और क़र्ज़ का एक हिस्सा होता है। शुरू में EMI का ज़्यादातर हिस्सा ब्याज होता है; समय के साथ ज़्यादा हिस्सा क़र्ज़ चुकाता है।"),
      (["Rate type matters: on a reducing-balance loan, interest is charged on what you still owe. A 'flat' rate charges on the original amount for the whole term, so a 'flat 10%' is roughly an effective 17 to 19% a year.",
        "Total cost = EMI × number of months. A longer tenure lowers the EMI but raises the total interest paid, sometimes by a lot.",
        "Prepaying early in the loan saves the most interest, because that is when most of the balance is outstanding. Check for prepayment charges (floating-rate home loans for individuals generally cannot charge them).",
        "Prepay or invest? If the loan rate is higher than what you reasonably expect to earn after tax, repaying is a sure return.",
        "Keep total EMIs within roughly 40% of your monthly income so one shock does not break you."],
       ["दर का प्रकार मायने रखता है: घटते शेष वाले क़र्ज़ में ब्याज उस पर लगता है जो अभी बाक़ी है। 'फ़्लैट' दर पूरी अवधि में मूल रक़म पर लगती है, इसलिए 'फ़्लैट 10%' लगभग 17 से 19% सालाना की असली दर के बराबर है।",
        "कुल लागत = EMI × महीनों की संख्या। लंबी अवधि EMI घटाती है पर कुल ब्याज बढ़ाती है, कभी-कभी बहुत।",
        "क़र्ज़ की शुरुआत में पहले चुकाना सबसे ज़्यादा ब्याज बचाता है, क्योंकि तब ज़्यादातर शेष बाक़ी रहता है। पूर्व-भुगतान शुल्क देखिए (व्यक्तियों के फ़्लोटिंग-दर गृह ऋण पर आम तौर पर यह नहीं लग सकता)।",
        "पहले चुकाएँ या निवेश करें? अगर क़र्ज़ की दर उससे ऊँची है जो आप कर के बाद वाजिब रूप से कमा सकते हैं, तो चुकाना पक्का रिटर्न है।",
        "कुल EMI अपनी मासिक आय के लगभग 40% के भीतर रखिए ताकि एक झटका आपको न तोड़े।"]),
      ("Always ask for the 'effective annual rate' and the total amount payable, in writing.", "हमेशा लिखित में 'प्रभावी वार्षिक दर' और कुल देय रक़म माँगिए।"),
      [("Is a moneylender charging 5 rupees per hundred fair?", "साहूकार का सैकड़े पर 5 रुपये ब्याज कितना है?")],
      tool=("rural", "Check what a loan really costs", "क़र्ज़ की असली लागत जाँचिए", {})),

    C("rent_vs_buy", "Loans", r"\b(buy|buying|purchase)\b.{0,25}\b(house|home|flat|apartment|property)\b.{0,25}\b(or|vs|versus)\b.{0,15}\b(rent|renting)\b|\b(rent|renting)\b.{0,15}\b(or|vs|versus)\b.{0,25}\b(buy|buying|own)\b|\b(house|home|flat|property)\b.{0,20}\b(better|good|worth)\b.{0,15}\b(invest\w*|buy)\b|\bshould i (buy|take) (a )?(house|home|flat)\b|\brent vs (buy|own)\b",
      ["is it better to buy a house or rent", "should I buy a flat or keep renting", "is buying a home a good investment", "rent vs buy"],
      ("Buying is not automatically better than renting. A home is where you live and a big, hard-to-sell, one-city bet at the same time. The honest comparison is the full monthly cost of owning against rent plus what the difference would earn if invested.",
       "ख़रीदना अपने-आप किराए से बेहतर नहीं होता। घर रहने की जगह भी है और साथ ही एक बड़ा, मुश्किल से बिकने वाला, एक शहर पर दाँव भी। ईमानदार तुलना है: मालिक होने की पूरी मासिक लागत बनाम किराया और उसके अंतर को निवेश करने पर होने वाली कमाई।"),
      (["Count everything on the owning side: the EMI (mostly interest in the early years), down payment that could have been invested, registration and stamp duty, maintenance, property tax and repairs.",
        "A common check: if the yearly rent is under about 3 to 3.5% of the home's price, renting and investing the difference often costs less. In many Indian cities rent is around 2 to 3%, which is why renting can win financially.",
        "Buying wins when you will stay for many years (often 7 to 10 or more), the price is within your means (EMI within about 40% of income, after an emergency fund), and you value stability and control.",
        "Renting wins when your job or city may change, you want your money in a diversified portfolio, or the price-to-rent ratio is very high.",
        "A house is a single asset in a single place: do not let it be the only thing you own."],
       ["ख़रीदने वाले पक्ष की सब चीज़ें गिनिए: EMI (शुरू के सालों में ज़्यादातर ब्याज), एडवांस जो निवेश हो सकता था, रजिस्ट्री और स्टांप ड्यूटी, रखरखाव, प्रॉपर्टी टैक्स और मरम्मत।",
        "आम जाँच: अगर सालाना किराया घर की क़ीमत के लगभग 3 से 3.5% से कम है तो किराए पर रहकर अंतर निवेश करना अक्सर सस्ता पड़ता है। कई भारतीय शहरों में किराया लगभग 2 से 3% है, इसीलिए किराया आर्थिक रूप से जीत सकता है।",
        "ख़रीदना तब जीतता है जब आप कई साल टिकेंगे (अक्सर 7 से 10 या ज़्यादा), क़ीमत आपकी पहुँच में हो (इमरजेंसी फ़ंड के बाद EMI आय के लगभग 40% के भीतर) और आप स्थिरता और नियंत्रण को महत्व दें।",
        "किराया तब जीतता है जब आपकी नौकरी या शहर बदल सकता है, आप पैसा विविध पोर्टफ़ोलियो में रखना चाहते हैं, या क़ीमत-से-किराया अनुपात बहुत ऊँचा है।",
        "घर एक जगह की एक संपत्ति है: उसे अपनी इकलौती संपत्ति मत बनने दीजिए।"]),
      ("Prices and rents differ by city and locality, so run your own numbers: the home loan and EMI notes above show what the loan really costs.", "भाव और किराए शहर और इलाक़े के अनुसार अलग होते हैं, इसलिए अपने आँकड़े ख़ुद लगाइए: ऊपर के होम लोन और EMI के नोट दिखाते हैं कि क़र्ज़ असल में कितना पड़ता है।"),
      [("How is EMI calculated?", "EMI कैसे निकलती है?"), ("How do I start investing?", "निवेश कैसे शुरू करूँ?")]),

    C("credit_card", "Loans", r"\b(credit card)\b.{0,40}\b(interest|debt|bill|minimum|due|trap|pay|paying|rewards?|worth|good|bad|use|using|limit)\b|\b(minimum due|revolving credit|card debt|card bill)\b|\bwhy (is|are) credit card\b",
      ["is it ok to pay only the minimum on my credit card", "how does credit card interest work", "is a credit card good or bad", "how to get out of credit card debt"],
      ("A credit card is a free short loan only if you pay the full bill by the due date. Pay less and interest is charged, commonly 3% or more a month (about 36% a year or more), on the whole amount from the purchase date.",
       "क्रेडिट कार्ड तभी मुफ़्त छोटा उधार है जब आप पूरा बिल नियत तारीख़ तक चुकाएँ। कम चुकाया तो ब्याज लगता है, आम तौर पर महीने का 3% या ज़्यादा (सालाना लगभग 36% या ज़्यादा), ख़रीद की तारीख़ से पूरी रक़म पर।"),
      (["Paying only the 'minimum due' keeps the debt alive for years and the interest outweighs what you repaid.",
        "Pay the full statement amount every month; set an auto-pay for the full amount.",
        "If you are already in card debt: stop using the card, pay the highest-rate balance first, and consider a lower-rate personal loan or a balance transfer only if you can clear it in the new term.",
        "Cash withdrawals on a card start charging interest immediately and carry a fee: avoid them.",
        "Your credit score rewards low usage (below about 30% of your limit) and on-time payments."],
       ["सिर्फ़ 'न्यूनतम देय' चुकाने से क़र्ज़ सालों ज़िंदा रहता है और ब्याज आपके चुकाए से भारी पड़ता है।",
        "हर महीने पूरी स्टेटमेंट रक़म चुकाइए; पूरी रक़म का ऑटो-पे लगाइए।",
        "पहले से कार्ड का क़र्ज़ हो तो: कार्ड चलाना बंद कीजिए, सबसे ऊँची दर वाला बकाया पहले चुकाइए, और कम दर का पर्सनल लोन या बैलेंस ट्रांसफ़र तभी सोचिए जब नई अवधि में पूरा चुका सकें।",
        "कार्ड से नक़द निकासी पर ब्याज तुरंत शुरू होता है और शुल्क भी लगता है: उससे बचिए।",
        "आपका क्रेडिट स्कोर कम उपयोग (सीमा के लगभग 30% से नीचे) और समय पर भुगतान को इनाम देता है।"]),
      ("Rates differ by bank and card, so read your own statement for the exact figure.", "दरें बैंक और कार्ड के अनुसार अलग हैं, इसलिए ठीक आँकड़े के लिए अपनी स्टेटमेंट पढ़िए।"),
      [("What is a credit score and why was my loan rejected?", "क्रेडिट स्कोर क्या है और मेरा लोन क्यों रद्द हुआ?")],
      tool=("rural", "See the credit-score guide", "क्रेडिट स्कोर गाइड देखिए", {})),

    C("budget_rule", "Saving", r"\b(50[/ ]?30[/ ]?20|budget(ing)?|monthly budget|how (to|do i) (save|manage) (money|my salary)|save more|spend less|track (my )?(spending|expenses)|salary (management|planning)|pay yourself first)\b",
      ["how to budget my salary", "what is the 50 30 20 rule", "how can I save more money every month", "how to track expenses"],
      ("A budget is just a plan for each month's income so you decide where it goes, instead of finding out afterwards. The simplest start is to pay yourself first: save a fixed share the day the salary arrives.",
       "बजट हर महीने की आय की योजना है ताकि आप तय करें कि पैसा कहाँ जाएगा, बाद में पता लगाने की जगह। सबसे सरल शुरुआत है पहले अपने को भुगतान: वेतन आते ही एक तय हिस्सा बचा दीजिए।"),
      (["The 50/30/20 rule of thumb: about 50% for needs (rent, food, bills, EMIs), 30% for wants, 20% for saving and paying off debt. Adjust it: in expensive cities needs may take more.",
        "Automate it: a standing instruction to a SIP or recurring deposit on salary day, so saving does not depend on willpower.",
        "Track for one month, by category. Most people find two or three categories that leak money.",
        "Fix the big items first (rent, EMI, insurance, school fees), then the small ones. A cheaper phone plan is nice; a lower rent is life-changing.",
        "Give every goal its own name and date: 'laptop, Dec', 'trip, June'. Named money gets saved."],
       ["50/30/20 का अंगूठे का नियम: लगभग 50% ज़रूरतों के लिए (किराया, खाना, बिल, EMI), 30% इच्छाओं के लिए, 20% बचत और क़र्ज़ चुकाने के लिए। इसे अपने हिसाब से ढालिए: महँगे शहरों में ज़रूरतें ज़्यादा ले सकती हैं।",
        "इसे स्वचालित कीजिए: वेतन के दिन SIP या आवर्ती जमा का स्थायी निर्देश, ताकि बचत इच्छाशक्ति पर निर्भर न रहे।",
        "एक महीने श्रेणी के हिसाब से लिखिए। ज़्यादातर लोगों को दो-तीन श्रेणियाँ मिलती हैं जहाँ पैसा रिसता है।",
        "पहले बड़ी चीज़ें ठीक कीजिए (किराया, EMI, बीमा, स्कूल फ़ीस), फिर छोटी। सस्ता फ़ोन प्लान अच्छा है; कम किराया ज़िंदगी बदल देता है।",
        "हर लक्ष्य को अपना नाम और तारीख़ दीजिए: 'लैपटॉप, दिसंबर', 'सैर, जून'। नाम वाला पैसा बचता है।"]),
      ("The right split is the one you will keep doing. Start with any amount, even ₹500.", "सही बँटवारा वही है जिसे आप निभा सकें। किसी भी रक़म से शुरू कीजिए, ₹500 से भी।"),
      [("Can I save 100 rupees a day for my daughter's marriage?", "बेटी की शादी के लिए रोज़ 100 रुपये बचाऊँ तो?")],
      tool=("rural", "Plan a daily saving", "रोज़ की बचत की योजना", {})),

    C("check_advisor", "Safety", r"\b(sebi|registered)\b.{0,30}\b(advisor|adviser|analyst|broker|ria|registered|check|verify|genuine|legit)\b|\b(check|verify|is)\b.{0,20}\b(advisor|adviser|broker|analyst|app|platform)\b.{0,25}\b(registered|sebi|genuine|legit|real|safe)\b|\b(finfluencer|influencer)\b|\b(youtube|instagram|telegram|whatsapp)\b.{0,20}\b(finance|stock|trading|investing|advice|tips?|guru|channel)\b|\b(finance|stock|trading|market) (youtuber|guru|channel|expert|coach|course)\b|\bmarket guru\b|\bhow (to|do i) (check|know|verify)\b.{0,25}\b(advisor|broker|app|platform|company)\b",
      ["how do I check if an advisor is sebi registered", "is this investment adviser genuine", "how to verify a broker", "should I follow finfluencers"],
      ("In India, only people registered with SEBI may give investment advice for a fee or run a research service, and you can check this yourself in a minute on SEBI's website.",
       "भारत में सिर्फ़ SEBI में पंजीकृत लोग ही शुल्क लेकर निवेश सलाह दे सकते हैं या शोध सेवा चला सकते हैं, और आप यह एक मिनट में SEBI की वेबसाइट पर ख़ुद जाँच सकते हैं।"),
      (["Search the name or registration number in SEBI's list of registered intermediaries (investment advisers, research analysts, brokers) on sebi.gov.in.",
        "Check that the registration is current and the business matches what they are offering. A registered broker is not automatically a registered adviser.",
        "Warning signs: guaranteed returns, 'sure-shot' tips, pressure to act today, asking you to pay into a personal account or UPI ID, and group invitations from strangers.",
        "Pay only to the registered entity's own bank account and keep the receipt. A registered adviser is not allowed to take your money to 'invest for you'.",
        "If something goes wrong, you can complain on SEBI's SCORES portal; for fraud also call 1930 or report at cybercrime.gov.in."],
       ["sebi.gov.in पर पंजीकृत मध्यस्थों की सूची (निवेश सलाहकार, शोध विश्लेषक, ब्रोकर) में नाम या पंजीकरण संख्या खोजिए।",
        "जाँचिए कि पंजीकरण चालू है और उनका कारोबार वही है जो वे दे रहे हैं। पंजीकृत ब्रोकर अपने-आप पंजीकृत सलाहकार नहीं होता।",
        "चेतावनी के संकेत: पक्का रिटर्न, 'सुनिश्चित' टिप, आज ही करने का दबाव, निजी खाते या UPI ID में पैसा माँगना और अजनबियों के ग्रुप के न्योते।",
        "सिर्फ़ पंजीकृत संस्था के अपने बैंक खाते में भुगतान कीजिए और रसीद रखिए। पंजीकृत सलाहकार आपका पैसा 'आपके लिए लगाने' के लिए नहीं ले सकता।",
        "कुछ ग़लत हो तो SEBI के SCORES पोर्टल पर शिकायत कीजिए; ठगी हो तो 1930 पर फ़ोन करें या cybercrime.gov.in पर रिपोर्ट कीजिए।"]),
      ("A SEBI registration means the person is regulated, not that every call they make is right.", "SEBI पंजीकरण का मतलब है कि व्यक्ति नियंत्रित है, यह नहीं कि उनकी हर सलाह सही है।"),
      [("Check a stock tip", "स्टॉक टिप जाँचिए"), ("I think I was scammed", "मुझे लगता है ठगी हुई")],
      tool=("protect", "Check a tip", "टिप जाँचिए", {"tool": "tip"}), tour="tip"),

    C("how_accurate", "About this app", r"\b(how (accurate|reliable|correct|trustworthy)|can i trust (the |these |your |this |you\b|jarvis|what you)|is (it|this|the answer|jarvis) (accurate|correct|reliable|right|true)|do you (make up|guess|hallucinate|invent)|where (does|do) (the )?(data|numbers?|figures?) come from|data source|how do you (know|calculate|work out)|ai (hallucinat\w+|mistake|wrong)|do you use (chatgpt|ai|an llm|gpt))\b",
      ["how accurate are your answers", "can I trust these numbers", "where does the data come from", "do you make up numbers", "do you use AI"],
      ("Every number you see comes from a calculator or from stored data with a date on it, not from a language model's guess. The model, when it is used at all, only helps pick which tool fits your question; it never writes the answer or a figure.",
       "आप जो भी संख्या देखते हैं वह किसी कैलकुलेटर या तारीख़ वाले सहेजे डेटा से आती है, किसी भाषा-मॉडल के अंदाज़े से नहीं। मॉडल, अगर इस्तेमाल होता भी है, तो सिर्फ़ यह चुनने में मदद करता है कि आपके सवाल के लिए कौन सा औज़ार ठीक है; वह जवाब या कोई आँकड़ा कभी नहीं लिखता।"),
      (["Prices and company numbers come from public sources and are stored with the date they were fetched, so the Research page tells you how old each kind of data is.",
        "Explanations are written by people in advance, in English and Hindi, and are shown as written. That is why the same question gets the same answer.",
        "Anything I cannot work out, I say so: missing data appears under 'what we could not check' rather than being guessed.",
        "Click any underlined number to see the formula and the exact inputs behind it.",
        "Nothing here is investment advice, and no answer says buy, sell or hold. The tools describe your situation; the decision stays with you."],
       ["भाव और कंपनी के आँकड़े सार्वजनिक स्रोतों से आते हैं और जिस तारीख़ को लाए गए उसके साथ सहेजे जाते हैं, इसलिए शोध पेज बताता है कि हर तरह का डेटा कितना पुराना है।",
        "स्पष्टीकरण लोगों ने पहले से अंग्रेज़ी और हिंदी में लिखे हैं और जैसे लिखे हैं वैसे ही दिखते हैं। इसीलिए एक ही सवाल का एक ही जवाब मिलता है।",
        "जो मैं निकाल नहीं सकता, उसे साफ़ कहता हूँ: ग़ायब डेटा अंदाज़े से भरने की जगह 'जो हम जाँच नहीं सके' में दिखता है।",
        "किसी रेखांकित संख्या पर क्लिक कीजिए, उसका सूत्र और ठीक इनपुट दिखेंगे।",
        "यहाँ कुछ भी निवेश सलाह नहीं, और कोई जवाब ख़रीदने, बेचने या रोकने को नहीं कहता। औज़ार आपकी स्थिति बयान करते हैं; फ़ैसला आपका रहता है।"]),
      ("Data can be a few weeks old and sources can have errors: always check the 'how current is this' panel.", "डेटा कुछ हफ़्ते पुराना हो सकता है और स्रोतों में ग़लतियाँ हो सकती हैं: 'यह कितना ताज़ा है' पैनल हमेशा देखिए।"),
      [("Show me how the research page works", "शोध पेज कैसे काम करता है दिखाइए"), ("Explain the audit record", "ऑडिट रिकॉर्ड समझाइए")],
      tour="research"),

    C("privacy", "About this app", r"\b(privacy|private|my data|data (safe|secure|stored|leave|shared)|where is (my )?data|is (my|the) data safe|offline|without internet|works offline|no internet|tracking|who can see)\b",
      ["is my data private", "where is my data stored", "does this work offline", "does my data leave my device"],
      ("Your data stays on this machine. Voice is turned into text locally, the calculators run locally, and the app can work offline once its pack is saved. Only fetching fresh prices uses the internet.",
       "आपका डेटा इसी मशीन पर रहता है। आवाज़ यहीं लिखत में बदलती है, कैलकुलेटर यहीं चलते हैं, और पैक सहेजने के बाद ऐप ऑफ़लाइन चल सकता है। सिर्फ़ ताज़ा भाव लाने में इंटरनेट इस्तेमाल होता है।"),
      (["Speech to text (faster-whisper) and the voice that reads answers (Piper or Kokoro) both run on this computer.",
        "Your portfolio, saved funds, rules and records are stored in a local database; nothing is sent to an outside service to answer a question.",
        "The offline pack saves the app and the calculators in your browser so a village with no signal can still use the tools.",
        "A kiosk mode wipes the previous person's answers before the next person uses a shared device.",
        "Fetching a new company's prices or opening an online chart does contact the internet; everything else does not."],
       ["बोली से लिखत (faster-whisper) और जवाब पढ़ने वाली आवाज़ (Piper या Kokoro) दोनों इसी कंप्यूटर पर चलती हैं।",
        "आपका पोर्टफ़ोलियो, सहेजे फ़ंड, नियम और रिकॉर्ड स्थानीय डेटाबेस में रहते हैं; सवाल का जवाब देने के लिए कुछ भी बाहरी सेवा को नहीं भेजा जाता।",
        "ऑफ़लाइन पैक ऐप और कैलकुलेटर को आपके ब्राउज़र में सहेज लेता है ताकि बिना सिग्नल का गाँव भी औज़ार इस्तेमाल कर सके।",
        "कियोस्क मोड साझा उपकरण पर अगला व्यक्ति आने से पहले पिछले व्यक्ति के जवाब मिटा देता है।",
        "किसी नई कंपनी के भाव लाने या ऑनलाइन चार्ट खोलने में इंटरनेट से संपर्क होता है; बाक़ी सब में नहीं।"]),
      ("On a shared device, use kiosk mode so the next person does not see your answers.", "साझा उपकरण पर कियोस्क मोड इस्तेमाल कीजिए ताकि अगला व्यक्ति आपके जवाब न देखे।"),
      [("Explain the rural tools", "ग्रामीण औज़ार समझाइए")],
      tour="settings"),
]

BY_ID = {c["id"]: c for c in CONCEPTS}


def keyword_hits(text: str) -> list[tuple[str, float]]:
    """Concepts whose pattern matches, scored by how much of the question the match covers."""
    out = []
    for c in CONCEPTS:
        m = c["rx"].search(text)
        if m:
            out.append((c["id"], 0.5 + min(0.5, len(m.group(0)) / max(20, len(text)))))
    return sorted(out, key=lambda kv: -kv[1])
