"""Scam recovery coach: what to do in the first hour, in what order, and the words to say.

After a scam, people lose the first hour to panic, shame and not knowing the sequence. This
module is deliberately plain data plus string templates: the steps, their urgency and the three
drafts (a 30-second phone script, a cybercrime-portal narrative and a letter to the bank) are
written once by hand in English and Hindi, and the person's own details are dropped in by code.
Nothing here is generated by a model and nothing guesses a fact the person did not give.

India specifics: 1930 is the national cyber-fraud helpline and cybercrime.gov.in the portal. RBI's
customer-protection rules make reporting speed matter for liability, but who is liable depends on
whose lapse it was, so the text says "ask in writing" rather than promising a refund.
"""
from __future__ import annotations

from typing import Any

TYPES: dict[str, dict[str, str]] = {
    "upi_card": {"en": "Money was taken from my account (UPI, card or net banking)",
                 "hi": "मेरे खाते से पैसे निकल गए (UPI, कार्ड या नेट बैंकिंग)",
                 "what_en": "an unauthorised transaction from my account", "what_hi": "मेरे खाते से बिना मंज़ूरी का लेन-देन"},
    "shared_code": {"en": "I shared an OTP, PIN, CVV or password",
                    "hi": "मैंने OTP, पिन, CVV या पासवर्ड बता दिया",
                    "what_en": "sharing an OTP/PIN/password with a fraudster", "what_hi": "ठग को OTP/पिन/पासवर्ड बताना"},
    "remote_app": {"en": "I installed a screen-sharing or remote app (AnyDesk, QuickSupport...)",
                   "hi": "मैंने स्क्रीन-शेयरिंग या रिमोट ऐप डाउनलोड किया (AnyDesk, QuickSupport...)",
                   "what_en": "a fraudster getting remote access to my phone", "what_hi": "ठग को मेरे फ़ोन का रिमोट एक्सेस मिलना"},
    "invest": {"en": "I paid into a fake investment, trading app or tips group",
               "hi": "मैंने नक़ली निवेश, ट्रेडिंग ऐप या टिप्स ग्रुप में पैसे डाले",
               "what_en": "paying into a fake investment/trading scheme", "what_hi": "नक़ली निवेश/ट्रेडिंग योजना में पैसे देना"},
    "digital_arrest": {"en": "Someone posing as police, CBI or customs made me transfer money",
                       "hi": "पुलिस, CBI या कस्टम बनकर किसी ने मुझसे पैसे भिजवाए",
                       "what_en": "a fraudster posing as a police/government officer", "what_hi": "पुलिस/सरकारी अधिकारी बनकर ठगी"},
    "link_clicked": {"en": "I clicked a link or entered details, but nothing has been taken yet",
                     "hi": "मैंने लिंक खोला या जानकारी भरी, पर अभी कुछ कटा नहीं",
                     "what_en": "clicking a phishing link / entering details on a fake page", "what_hi": "फ़िशिंग लिंक खोलना / नक़ली पेज पर जानकारी भरना"},
}

# id -> (minutes within which it matters most, title, detail) in each language
STEPS: dict[str, dict[str, Any]] = {
    "stop_payments": {"mins": 0,
        "en": ("Stop paying. Do not send anything more", "Do not pay any 'release fee', 'tax', 'penalty' or 'recovery agent'. Real recovery never asks for money upfront; anyone who does is the second scam. Do not follow their instructions to 'keep this secret'."),
        "hi": ("और पैसे मत भेजिए", "कोई 'रिलीज़ फ़ीस', 'टैक्स', 'जुर्माना' या 'रिकवरी एजेंट' का पैसा मत दीजिए। असली रिकवरी में पहले पैसा नहीं माँगा जाता; जो माँगे वही दूसरी ठगी है। 'यह राज़ रखिए' वाली बात मत मानिए।")},
    "remove_app": {"mins": 5,
        "en": ("Cut the caller's access to your phone", "Switch on airplane mode or turn off Wi-Fi and data. Uninstall the remote app (AnyDesk, TeamViewer, QuickSupport, etc.). If you are unsure what else was installed, back up photos and do a factory reset."),
        "hi": ("ठग की पहुँच अपने फ़ोन से काटिए", "एयरप्लेन मोड चालू कीजिए या वाई-फ़ाई और डेटा बंद कीजिए। रिमोट ऐप (AnyDesk, TeamViewer, QuickSupport आदि) हटा दीजिए। और क्या इंस्टॉल हुआ, पक्का न हो तो फ़ोटो का बैकअप लेकर फ़ैक्टरी रीसेट कीजिए।")},
    "block_bank": {"mins": 15,
        "en": ("Call your bank's official helpline and block everything", "Use the number printed on your card or on the bank's own website, never one the caller gave or a search ad. Ask them to block the card, UPI and net banking, and to flag the transaction as fraud. Write down the complaint number they give you."),
        "hi": ("अपने बैंक की आधिकारिक हेल्पलाइन पर फ़ोन कर सब कुछ ब्लॉक करवाइए", "कार्ड पर छपे या बैंक की अपनी वेबसाइट के नंबर पर फ़ोन कीजिए, ठग के दिए नंबर या सर्च विज्ञापन पर नहीं। कार्ड, UPI और नेट बैंकिंग ब्लॉक करवाइए और लेन-देन को धोखाधड़ी बताइए। जो शिकायत नंबर मिले उसे लिख लीजिए।")},
    "change_credentials": {"mins": 30,
        "en": ("Change PINs and passwords from a safe device", "Change the UPI PIN, net-banking password and your email password, and any other account that uses the same one. Turn on two-step sign-in. Do this on a device the fraudster never touched."),
        "hi": ("सुरक्षित डिवाइस से पिन और पासवर्ड बदलिए", "UPI पिन, नेट बैंकिंग पासवर्ड और ईमेल पासवर्ड बदलिए, साथ ही वे सभी खाते जिनमें यही पासवर्ड है। टू-स्टेप साइन-इन चालू कीजिए। यह उस डिवाइस से कीजिए जिसे ठग ने कभी छुआ नहीं।")},
    "report_1930": {"mins": 60,
        "en": ("Report to 1930 and cybercrime.gov.in", "Call 1930 (the national cyber-fraud helpline) or file on cybercrime.gov.in. Report within the first hour if you can: it gives the best chance of freezing the account that received the money. Keep ready: amount, date and time, transaction ID/UTR, the account, UPI ID or phone number the money went to."),
        "hi": ("1930 और cybercrime.gov.in पर शिकायत कीजिए", "1930 (राष्ट्रीय साइबर ठगी हेल्पलाइन) पर फ़ोन कीजिए या cybercrime.gov.in पर शिकायत दर्ज कीजिए। हो सके तो पहले घंटे में कीजिए: पैसा पाने वाला खाता फ़्रीज़ होने की सबसे अच्छी संभावना तब होती है। तैयार रखिए: रक़म, तारीख़ और समय, ट्रांज़ैक्शन आईडी/UTR, और जिस खाते, UPI आईडी या फ़ोन नंबर पर पैसे गए।")},
    "evidence": {"mins": 60,
        "en": ("Keep the evidence. Do not delete anything", "Screenshot chats, call logs, the caller's number, UPI IDs, the website or app and the payment receipts. Do not delete chats or uninstall an investment app until you have saved copies."),
        "hi": ("सबूत सँभालकर रखिए, कुछ मत मिटाइए", "चैट, कॉल लॉग, कॉल करने वाले का नंबर, UPI आईडी, वेबसाइट या ऐप और भुगतान की रसीदों के स्क्रीनशॉट लीजिए। कॉपी सहेजने से पहले चैट मत मिटाइए और निवेश ऐप अनइंस्टॉल मत कीजिए।")},
    "sebi_check": {"mins": 1440,
        "en": ("Check whether the platform or adviser is registered", "Look the name up on sebi.gov.in under Intermediaries. Fake trading apps often show fake profits and block withdrawals. If a registered entity was impersonated, you can also complain on SEBI's SCORES portal."),
        "hi": ("जाँचिए कि वह प्लेटफ़ॉर्म या सलाहकार पंजीकृत है या नहीं", "नाम sebi.gov.in पर Intermediaries में खोजिए। नक़ली ट्रेडिंग ऐप अक्सर नक़ली मुनाफ़ा दिखाते हैं और पैसा निकालने नहीं देते। किसी पंजीकृत संस्था का नाम इस्तेमाल हुआ हो तो SEBI के SCORES पोर्टल पर भी शिकायत कर सकते हैं।")},
    "bank_letter": {"mins": 4320,
        "en": ("Send the bank a written dispute within 3 working days", "Email it and keep a copy, or submit it at the branch and get a stamped receipt (draft below). Under RBI's customer-protection rules, reporting an unauthorised electronic transaction quickly can limit or remove your liability. Who bears the loss depends on whose lapse it was, so do not assume you cannot be refunded: ask in writing."),
        "hi": ("3 कामकाजी दिनों में बैंक को लिखित शिकायत भेजिए", "ईमेल कीजिए और कॉपी रखिए, या शाखा में जमा कर मुहर लगी रसीद लीजिए (नीचे मसौदा है)। RBI के ग्राहक-सुरक्षा नियमों में, बिना मंज़ूरी के इलेक्ट्रॉनिक लेन-देन की जल्दी सूचना देने पर आपकी ज़िम्मेदारी सीमित या ख़त्म हो सकती है। नुक़सान किसकी चूक से हुआ, इस पर निर्भर करता है कि कौन भरेगा, इसलिए मान मत लीजिए कि पैसा नहीं मिलेगा: लिखकर माँगिए।")},
    "fir": {"mins": 1440,
        "en": ("File a police complaint or FIR, especially for a large amount", "Go to your local police station or the cyber police station with the evidence and your portal complaint number. Ask for an acknowledgement or FIR copy. Banks and courts take a written record seriously."),
        "hi": ("पुलिस में शिकायत या FIR दर्ज कराइए, ख़ासकर बड़ी रक़म हो तो", "सबूत और पोर्टल के शिकायत नंबर के साथ नज़दीकी थाने या साइबर थाने जाइए। पावती या FIR की कॉपी माँगिए। बैंक और अदालतें लिखित रिकॉर्ड को गंभीरता से लेती हैं।")},
    "aadhaar_lock": {"mins": 1440,
        "en": ("Protect your identity documents", "If you entered or sent Aadhaar, PAN or selfies, lock your Aadhaar biometrics in the mAadhaar app or on uidai.gov.in, and check your credit report for loans you did not take. If a SIM was involved, tell your mobile operator."),
        "hi": ("अपने पहचान-पत्रों को सुरक्षित कीजिए", "आधार, पैन या सेल्फ़ी भरी या भेजी हो तो mAadhaar ऐप या uidai.gov.in पर अपना आधार बायोमेट्रिक लॉक कीजिए, और क्रेडिट रिपोर्ट में देखिए कि आपके नाम पर कोई ऐसा लोन तो नहीं जो आपने नहीं लिया। सिम का मामला हो तो मोबाइल कंपनी को बताइए।")},
    "monitor": {"mins": 10080,
        "en": ("Watch your accounts for the next 30 days", "Turn on SMS and app alerts for every transaction, check statements, and be ready for follow-up calls from 'recovery agents' or the same fraudster. Hang up on them."),
        "hi": ("अगले 30 दिन अपने खाते देखते रहिए", "हर लेन-देन के SMS और ऐप अलर्ट चालू कीजिए, स्टेटमेंट जाँचिए, और 'रिकवरी एजेंट' या उसी ठग के दोबारा आने वाले फ़ोन के लिए तैयार रहिए। उन पर फ़ोन काट दीजिए।")},
    "tell_family": {"mins": 0,
        "en": ("Tell someone you trust", "Scammers depend on secrecy and shame. Telling a family member or friend helps you think clearly, and many people have lost money this way. It is not your fault."),
        "hi": ("किसी भरोसेमंद को बताइए", "ठग चुप्पी और शर्म पर टिके होते हैं। घर के किसी सदस्य या दोस्त को बताने से आप साफ़ सोच पाते हैं, और बहुत लोग इसी तरह पैसे खो चुके हैं। यह आपकी ग़लती नहीं है।")},
}

PLAN: dict[str, list[str]] = {
    "upi_card": ["block_bank", "report_1930", "evidence", "bank_letter", "change_credentials", "fir", "monitor", "tell_family"],
    "shared_code": ["block_bank", "change_credentials", "report_1930", "evidence", "bank_letter", "monitor", "tell_family"],
    "remote_app": ["remove_app", "block_bank", "change_credentials", "report_1930", "evidence", "bank_letter", "monitor", "tell_family"],
    "invest": ["stop_payments", "report_1930", "evidence", "sebi_check", "bank_letter", "fir", "tell_family", "monitor"],
    "digital_arrest": ["stop_payments", "block_bank", "report_1930", "evidence", "bank_letter", "fir", "tell_family", "monitor"],
    "link_clicked": ["change_credentials", "block_bank", "aadhaar_lock", "evidence", "report_1930", "monitor", "tell_family"],
}


def types(lang: str = "en") -> list[dict[str, str]]:
    return [{"id": k, "label": v["hi" if lang == "hi" else "en"]} for k, v in TYPES.items()]


def plan(kind: str, lang: str = "en") -> dict[str, Any]:
    """The ordered steps for what happened. `mins` is how long the step stays most useful."""
    if kind not in PLAN:
        kind = "upi_card"
    hi = lang == "hi"
    steps = []
    for i, sid in enumerate(PLAN[kind]):
        s = STEPS[sid]
        title, detail = s["hi" if hi else "en"]
        steps.append({"id": sid, "n": i + 1, "title": title, "detail": detail, "mins": s["mins"]})
    return {"type": kind, "label": TYPES[kind]["hi" if hi else "en"], "steps": steps, "lang": lang,
            "helpline": "1930", "portal": "cybercrime.gov.in"}


def _val(x: Any, placeholder: str) -> str:
    x = ("" if x is None else str(x)).strip()
    return x or placeholder


def drafts(kind: str, lang: str = "en", amount: float | None = None, when: str = "", txn_id: str = "",
           fraud_contact: str = "", bank: str = "", name: str = "") -> dict[str, str]:
    """Three ready-to-use texts with the person's details filled in; gaps are shown as [brackets]."""
    from analysis import tools
    hi = lang == "hi"
    kind = kind if kind in TYPES else "upi_card"
    what = TYPES[kind]["what_hi" if hi else "what_en"]
    amt = (tools.inr_hi(amount) if hi else tools.inr(amount)) if amount else ("[रक़म]" if hi else "[amount]")
    w = _val(when, "[तारीख़ और समय]" if hi else "[date and time]")
    t = _val(txn_id, "[ट्रांज़ैक्शन आईडी/UTR]" if hi else "[transaction ID / UTR]")
    f = _val(fraud_contact, "[ठग का फ़ोन नंबर / UPI आईडी / खाता]" if hi else "[fraudster's phone number / UPI ID / account]")
    b = _val(bank, "[बैंक का नाम]" if hi else "[bank name]")
    n = _val(name, "[आपका नाम]" if hi else "[your name]")
    if hi:
        script = (f"नमस्ते, मैं {n} बोल रहा/रही हूँ। मेरे साथ साइबर ठगी हुई है: {what}। रक़म {amt} है, समय {w}। "
                  f"ट्रांज़ैक्शन आईडी {t}। पैसे इस पर गए: {f}। कृपया मेरा कार्ड, UPI और नेट बैंकिंग अभी ब्लॉक कीजिए, "
                  f"इस लेन-देन को धोखाधड़ी दर्ज कीजिए और मुझे शिकायत नंबर दीजिए।")
        portal = (f"घटना: {what}। तारीख़ और समय: {w}। खोई हुई रक़म: {amt}। ट्रांज़ैक्शन आईडी/UTR: {t}। "
                  f"जिस खाते/UPI आईडी/फ़ोन नंबर पर पैसे गए या जिसने संपर्क किया: {f}। मेरा बैंक: {b}। "
                  f"मैंने बैंक को सूचित कर दिया है और सबूत (स्क्रीनशॉट, चैट, रसीदें) सहेज लिए हैं। "
                  f"अनुरोध है कि प्राप्तकर्ता खाते को फ़्रीज़ करने और रक़म लौटाने की कार्रवाई की जाए।")
        letter = (f"प्रति,\nशाखा प्रबंधक, {b}\n\nविषय: बिना मंज़ूरी के इलेक्ट्रॉनिक लेन-देन की शिकायत और विवाद\n\n"
                  f"महोदय/महोदया,\n\nमैं, {n}, सूचित करता/करती हूँ कि {w} को मेरे खाते से {amt} का लेन-देन हुआ (ट्रांज़ैक्शन आईडी: {t}), "
                  f"जो मेरी जानकारी और मंज़ूरी के बिना ठगी के कारण हुआ ({what})। पैसे इस पर गए: {f}।\n\n"
                  f"मैंने इसकी सूचना आपकी हेल्पलाइन और राष्ट्रीय साइबर अपराध पोर्टल (1930) पर तुरंत दी है। "
                  f"कृपया इस लेन-देन को विवादित दर्ज कीजिए, प्राप्तकर्ता बैंक को सूचित कीजिए, मेरी देयता की RBI के ग्राहक-सुरक्षा नियमों के अनुसार समीक्षा कीजिए "
                  f"और लिखित में मुझे उत्तर दीजिए।\n\nधन्यवाद,\n{n}")
        return {"script": script, "portal": portal, "letter": letter}
    script = (f"Hello, this is {n}. I have been the victim of a cyber fraud: {what}. The amount is {amt}, at {w}. "
              f"Transaction ID {t}. The money went to: {f}. Please block my card, UPI and net banking right now, "
              f"record this transaction as fraud, and give me a complaint number.")
    portal = (f"Incident: {what}. Date and time: {w}. Amount lost: {amt}. Transaction ID / UTR: {t}. "
              f"Account, UPI ID or phone number the money went to or that contacted me: {f}. My bank: {b}. "
              f"I have informed my bank and saved the evidence (screenshots, chats, receipts). "
              f"I request action to freeze the receiving account and recover the amount.")
    letter = (f"To,\nThe Branch Manager, {b}\n\nSubject: Complaint and dispute of an unauthorised electronic transaction\n\n"
              f"Sir/Madam,\n\nI, {n}, report that on {w} a transaction of {amt} (transaction ID: {t}) was made from my account "
              f"without my knowledge or consent because of a fraud ({what}). The money went to: {f}.\n\n"
              f"I have reported this on your helpline and to the national cyber-crime helpline (1930) immediately. "
              f"Please record this transaction as disputed, inform the receiving bank, review my liability under RBI's customer-protection rules, "
              f"and reply to me in writing.\n\nThank you,\n{n}")
    return {"script": script, "portal": portal, "letter": letter}


def guess_type(text: str) -> str:
    """Which situation a sentence describes (for the chatbot). Order matters: the more specific
    and more urgent situations first."""
    import re
    t = text.lower()
    if re.search(r"anydesk|teamviewer|quicksupport|screen[- ]?shar|remote (access|app|control)|installed .*app|install(ed)? (an? )?app", t):
        return "remote_app"
    if re.search(r"arrest|police|cbi|customs|warrant|parcel|court|income tax", t):
        return "digital_arrest"
    if re.search(r"invest|trading|stock|crypto|demat|tips?|group|returns?|profit|forex", t):
        return "invest"
    if re.search(r"\botp\b|\bpin\b|cvv|password|code", t):
        return "shared_code"
    if re.search(r"link|clicked|website|form|kyc update|filled", t):
        return "link_clicked"
    return "upi_card"


def when_label(mins: int, hi: bool = False) -> str:
    """How soon a step matters, in words."""
    if mins <= 0:
        return "अभी" if hi else "now"
    if mins < 60:
        return f"{mins} मिनट में" if hi else f"within {mins} minutes"
    if mins == 60:
        return "1 घंटे में" if hi else "within 1 hour"
    if mins <= 1440:
        return "24 घंटे में" if hi else "within 24 hours"
    if mins <= 4320:
        return "3 कामकाजी दिनों में" if hi else "within 3 working days"
    return "अगले 30 दिन" if hi else "over the next 30 days"
