"""Runs ten varied sample tips through the checker and writes docs/TIP_TEST_SAMPLES.md. Run: python -m tools.tip_samples"""
from pathlib import Path

from analysis import tipminds
from backend.session import Session

SAMPLES = [
    ("1. Loud classic pump", "Should be flagged red", "SURE SHOT 10x multibagger!! TCS profit up 300%, target Rs 9000. Buy now before Monday, insider news. Join my VIP telegram t.me/xyz. 100% guaranteed returns."),
    ("2. Calm bare call, no reason", "Amber: calm wording is not evidence", "I have been tracking Infosys for a while and I think it is a good time to buy. Looks like it will go up soon. Target 1500."),
    ("3. Polite request for account access", "Red: asking for login or money is decisive", "Kindly share your demat login with me and I will trade on your behalf. Results will be good. Registration fee 5000."),
    ("4. Polite fixed monthly return", "Red: a steady periodic return is a Ponzi-style marker", "Our plan gives 4% return every month, steady monthly income, withdraw anytime. Start with 50000 and refer friends."),
    ("5. Track record as proof", "Red or amber: unverifiable proof plus a fast target", "My last 10 calls all hit target, accuracy 92%. Reliance looks strong now, buy for target 1700 in 2 weeks."),
    ("6. Qualitative claims that the data can test (Titan)", "Claims are checked: 'debt free' should be contradicted", "Titan is debt free with strong growth and looks undervalued. Good buy for the next few months."),
    ("7. Technical claim the chart can test (SBIN)", "'Breakout' is checked against the 52-week range", "SBIN is at a breakout above its 52 week high, strong momentum, buy."),
    ("8. Tiny stock, secrecy, no risk", "Amber/red: penny stock, secrecy, risk denial", "Do not share this. Penny stock under Rs 10, tiny company ready to rocket, low risk, only for selected members."),
    ("9. Unknown company", "Cannot be checked; says so", "ZOMATO will double soon, buy ZOMATO before it runs."),
    ("10. Plain factual note", "Green but still not advice", "Wipro will announce its quarterly results next week."),
]


def main() -> None:
    s = Session.create()
    out = ["# Tip checker: sample tips and what the checker does with them", "",
           "Generated by `python -m tools.tip_samples`. Each row is what the checker returned on this machine's data, with the reasons it gave.", ""]
    for title, expect, text in SAMPLES:
        r = tipminds.analyse_sync(s.pit, text)
        out += [f"## {title}", f"*Expected: {expect}*", "", f"> {text}", "",
                f"**{r['verdict']}**  (scam likelihood {r['scam_likelihood']}%, backing {r['reliability']}/100, action: {r['action']})", "",
                f"*Understood as:* {r['reading']['action']} on {', '.join(r['reading']['instruments']) or 'no identified stock'}; target {r['reading']['target_price']}; horizon {r['reading']['horizon_days']} days; asks {r['reading']['asks'] or 'nothing'}; reasons offered {r['reading']['thesis'] or 'none'}.", ""]
        for f in r["agents"]:
            out.append(f"- **{f['agent']}** ({f['stance']}): {f['headline']}. {f['reasoning']}")
        out += ["", "What to do:"] + [f"{i + 1}. {x}" for i, x in enumerate(r["steps"])] + [""]
    Path(__file__).resolve().parent.parent.joinpath("docs", "TIP_TEST_SAMPLES.md").write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
